import { test, expect } from '@playwright/test';

// Visual regression baselines are Linux-only by necessity: Playwright's
// screenshot comparison is sensitive to OS-level font rendering, and this
// repo's CI runs on ubuntu-latest while local development here is macOS —
// a baseline generated on macOS would never match CI and would make every
// PR fail on unrelated font-antialiasing differences. Baselines are
// generated by the "Generate Visual Baselines" workflow (workflow_dispatch,
// runs on ubuntu-latest) and committed under e2e/visual.spec.ts-snapshots/ —
// never generate/update them from a local macOS run. See docs/e2e-testing.md.
//
// Scoped to the same client-side-only, unauthenticated pages as
// login.spec.ts for the same reason: no dedicated test Supabase project
// exists, so nothing here can touch real backend state.
test.describe('Visual regression', () => {
  test('login page (sign-in mode)', async ({ page }) => {
    await page.goto('/login');
    await expect(page.getByRole('heading', { name: 'Welcome Back' })).toBeVisible();
    await expect(page).toHaveScreenshot('login-signin.png', { maxDiffPixelRatio: 0.02 });
  });

  test('login page (sign-up mode)', async ({ page }) => {
    await page.goto('/login');
    await page.getByRole('button', { name: 'Sign Up' }).first().click();
    await expect(page.getByRole('heading', { name: 'Create Account' })).toBeVisible();
    await expect(page).toHaveScreenshot('login-signup.png', { maxDiffPixelRatio: 0.02 });
  });
});
