// ═══════════════════════════════════════════════════════════════════════════
// ParentPortalPage — Parent Mode
// Route: /parent-portal
//
// Dual-mode page:
//   STUDENT view  → generate invite code to share with parent
//   PARENT view   → enter invite code → linked dashboard of child's stats
//
// Architecture:
//   • `parent_invite_codes` — time-limited codes generated by students
//   • `parent_child_links`  — permanent parent↔child relationships
//   • `parent-link` edge fn — generates codes, accepts codes, fetches stats
//     (uses service-role key so parent can read child's RLS-protected data)
//
// Page phases:
//   'loading'         → checking existing links
//   'student_setup'   → student sees invite code + existing link status
//   'enter_code'      → parent mode: enter 6-char code from child
//   'parent_dashboard'→ parent sees full child stats dashboard
// ═══════════════════════════════════════════════════════════════════════════

import { useState, useEffect, useCallback, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ArrowLeft, Users, RefreshCw, Share2, Copy, Check,
  TrendingUp, Zap, Flame, Clock, BookOpen, Target,
  ChevronRight, Loader2, Award, AlertCircle, Shield,
  BarChart2, Brain, Trophy, X,
} from 'lucide-react';
import { Link } from 'react-router-dom';
import { Share } from '@capacitor/share';
import { Capacitor } from '@capacitor/core';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/lib/supabase';

// ── Types ─────────────────────────────────────────────────────────────────────

interface ChildLink {
  child_id:   string;
  child_name: string;
  linked_at:  string;
}

interface WeakTopic {
  topic:    string;
  subject:  string;
  accuracy: number;
}

interface SubjectStat {
  subject:              string;
  accuracy:             number;
  questions_attempted:  number;
}

interface RecentActivity {
  type:       string;
  subject:    string;
  created_at: string;
  score:      number | null;
}

interface ChildStats {
  profile: {
    full_name:     string;
    xp:            number;
    level:         number;
    streak_count:  number;
  };
  week: {
    study_minutes:      number;
    quiz_accuracy:      number;
    xp_earned:          number;
    sessions_completed: number;
  };
  subjects:        SubjectStat[];
  recent_activity: RecentActivity[];
  boss_fights: {
    total:     number;
    victories: number;
    last_boss: string | null;
  };
  weak_topics:  WeakTopic[];
  xp_history:   Array<{ date: string; xp: number }>;
}

type Phase = 'loading' | 'student_setup' | 'enter_code' | 'parent_dashboard';

// ── Constants ─────────────────────────────────────────────────────────────────

const SUBJECT_COLORS: Record<string, string> = {
  Physics:     '#5B6AF5',
  Chemistry:   '#10B981',
  Mathematics: '#F59E0B',
  Biology:     '#EC4899',
};

function timeAgo(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  const m = Math.floor(diff / 60000);
  if (m < 1)  return 'just now';
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

function invokeFn(action: string, body: Record<string, unknown>) {
  return supabase.functions.invoke('parent-link', { body: { action, ...body } });
}

// ── XP Mini-bar ───────────────────────────────────────────────────────────────

function XPBar({ value, max, color = '#5B6AF5' }: { value: number; max: number; color?: string }) {
  const pct = max > 0 ? Math.min(100, Math.round((value / max) * 100)) : 0;
  return (
    <div className="w-full h-2 rounded-full bg-white/10 overflow-hidden">
      <motion.div
        className="h-full rounded-full"
        style={{ background: color }}
        initial={{ width: 0 }}
        animate={{ width: `${pct}%` }}
        transition={{ duration: 0.8, ease: 'easeOut' }}
      />
    </div>
  );
}

// ── Weekly XP Chart ───────────────────────────────────────────────────────────

function WeeklyChart({ history }: { history: Array<{ date: string; xp: number }> }) {
  const max = Math.max(...history.map((h) => h.xp), 1);
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  return (
    <div className="flex items-end gap-1 h-16">
      {history.map((h, i) => {
        const pct = (h.xp / max) * 100;
        return (
          <div key={i} className="flex-1 flex flex-col items-center gap-1">
            <motion.div
              className="w-full rounded-t-sm"
              style={{ background: '#5B6AF5', minHeight: 2 }}
              initial={{ height: 0 }}
              animate={{ height: `${Math.max(4, pct)}%` }}
              transition={{ duration: 0.6, delay: i * 0.05, ease: 'easeOut' }}
            />
            <span className="text-[8px] text-gray-600">{days[i % 7]}</span>
          </div>
        );
      })}
    </div>
  );
}

// ── Main Component ─────────────────────────────────────────────────────────────

export default function ParentPortalPage() {
  const { user, profile } = useAuth();

  const [phase, setPhase]               = useState<Phase>('loading');
  const [childLinks, setChildLinks]     = useState<ChildLink[]>([]);
  const [selectedChild, setSelectedChild] = useState<ChildLink | null>(null);
  const [childStats, setChildStats]     = useState<ChildStats | null>(null);
  const [statsLoading, setStatsLoading] = useState(false);

  // Student invite
  const [inviteCode, setInviteCode]   = useState<string | null>(null);
  const [codeLoading, setCodeLoading] = useState(false);
  const [codeCopied, setCodeCopied]   = useState(false);
  const [studentLinks, setStudentLinks] = useState<{ parent_name: string; linked_at: string }[]>([]);

  // Parent enter code
  const [enteredCode, setEnteredCode] = useState('');
  const [codeError, setCodeError]     = useState('');
  const [accepting, setAccepting]     = useState(false);

  const refreshRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // ── Bootstrap ────────────────────────────────────────────────────────────
  const bootstrap = useCallback(async () => {
    if (!user) return;

    // Check if this user IS a parent (has child links)
    const { data: childLinksData } = await invokeFn('get_children', { parent_id: user.id });
    const children = (childLinksData?.children ?? []) as ChildLink[];

    // Check if this user IS a student (has parent links)
    const { data: parentLinksData } = await invokeFn('get_parents', { child_id: user.id });
    const parents = (parentLinksData?.parents ?? []) as { parent_name: string; linked_at: string }[];

    if (children.length > 0) {
      setChildLinks(children);
      setSelectedChild(children[0]);
      setPhase('parent_dashboard');
    } else {
      setStudentLinks(parents);
      setPhase('student_setup');
    }
  }, [user]);

  useEffect(() => { bootstrap(); }, [bootstrap]);

  // ── Load child stats ──────────────────────────────────────────────────────
  const loadChildStats = useCallback(async (childId: string) => {
    setStatsLoading(true);
    const { data } = await invokeFn('get_child_stats', { child_id: childId });
    if (data?.stats) setChildStats(data.stats as ChildStats);
    setStatsLoading(false);
  }, []);

  useEffect(() => {
    if (phase === 'parent_dashboard' && selectedChild) {
      loadChildStats(selectedChild.child_id);
      refreshRef.current = setInterval(() => loadChildStats(selectedChild.child_id), 5 * 60 * 1000);
    }
    return () => { if (refreshRef.current) clearInterval(refreshRef.current); };
  }, [phase, selectedChild, loadChildStats]);

  // ── Generate invite code ──────────────────────────────────────────────────
  const generateCode = async () => {
    if (!user) return;
    setCodeLoading(true);
    const { data } = await invokeFn('generate_code', { student_id: user.id });
    if (data?.code) setInviteCode(data.code as string);
    setCodeLoading(false);
  };

  // ── Copy / share code ─────────────────────────────────────────────────────
  const shareCode = async () => {
    if (!inviteCode) return;
    const name = (profile as { full_name?: string } | null)?.full_name ?? 'your child';
    const text = `Use code ${inviteCode} in the Edora app to see ${name}'s study progress.`;
    if (Capacitor.isNativePlatform()) {
      await Share.share({ title: 'Edora Parent Access', text }).catch(() => {});
    } else {
      await navigator.clipboard.writeText(text).catch(() => {});
      setCodeCopied(true);
      setTimeout(() => setCodeCopied(false), 2000);
    }
  };

  const copyCode = () => {
    if (!inviteCode) return;
    navigator.clipboard.writeText(inviteCode).catch(() => {});
    setCodeCopied(true);
    setTimeout(() => setCodeCopied(false), 2000);
  };

  // ── Accept invite code (parent) ───────────────────────────────────────────
  const acceptCode = async () => {
    const code = enteredCode.trim().toUpperCase();
    if (code.length !== 6) { setCodeError('Enter a valid 6-character code'); return; }
    setCodeError('');
    setAccepting(true);

    const { data, error } = await invokeFn('accept_code', { code, parent_id: user?.id });
    if (error || data?.error) {
      setCodeError(data?.error ?? 'Invalid or expired code');
      setAccepting(false);
      return;
    }

    setAccepting(false);
    bootstrap();
  };

  // ── Loading ───────────────────────────────────────────────────────────────
  if (phase === 'loading') {
    return (
      <div className="h-full flex items-center justify-center">
        <Loader2 className="w-8 h-8 text-indigo-400 animate-spin" />
      </div>
    );
  }

  // ── Student Setup Phase ───────────────────────────────────────────────────
  if (phase === 'student_setup') {
    return (
      <div className="h-full text-white flex flex-col">
        <div className="sticky top-0 z-20 border-b border-white/10 px-4 py-3 flex items-center gap-3 shrink-0" style={{ background: 'rgba(8,6,20,0.82)', backdropFilter: 'blur(48px) saturate(200%) brightness(1.04)', WebkitBackdropFilter: 'blur(48px) saturate(200%) brightness(1.04)' }}>
          <Link to="/home" className="p-2 rounded-xl hover:bg-white/5">
            <ArrowLeft className="w-5 h-5 text-gray-400" />
          </Link>
          <div className="flex-1">
            <h1 className="font-bold text-white">Parent Mode</h1>
            <p className="text-xs text-gray-400">Let your parents track your progress</p>
          </div>
          <button
            onClick={() => setPhase('enter_code')}
            className="px-3 py-1.5 rounded-xl border border-white/10 text-xs text-gray-400 hover:bg-white/5"
          >
            I'm a parent
          </button>
        </div>

        <div className="flex-1 overflow-y-auto pb-nav">
        <div className="max-w-md mx-auto px-4 py-8 space-y-6">
          {/* Hero */}
          <div className="text-center space-y-2">
            <div className="text-5xl">👨‍👩‍👧</div>
            <h2 className="text-xl font-bold">Keep your parents in the loop</h2>
            <p className="text-sm text-gray-400">
              Generate a code and share it with your parent. They'll get a live dashboard of your study progress.
            </p>
          </div>

          {/* Linked parents */}
          {studentLinks.length > 0 && (
            <div className="space-y-2">
              <p className="text-xs font-medium text-gray-500 uppercase tracking-wider">Connected Parents</p>
              {studentLinks.map((p, i) => (
                <div key={i} className="flex items-center gap-3 p-3 rounded-xl bg-emerald-900/20 border border-emerald-500/20">
                  <div className="w-8 h-8 rounded-full bg-emerald-600 flex items-center justify-center text-sm font-bold">
                    {p.parent_name[0]?.toUpperCase()}
                  </div>
                  <div>
                    <div className="text-sm text-white font-medium">{p.parent_name}</div>
                    <div className="text-xs text-gray-500">Linked {timeAgo(p.linked_at)}</div>
                  </div>
                  <Shield className="w-4 h-4 text-emerald-400 ml-auto" />
                </div>
              ))}
            </div>
          )}

          {/* Generate code */}
          <div className="p-5 rounded-2xl bg-white/5 border border-white/10 space-y-4">
            <div className="flex items-center gap-2 text-sm font-semibold text-white">
              <Users className="w-4 h-4 text-indigo-400" />
              Generate Parent Invite Code
            </div>

            {inviteCode ? (
              <div className="space-y-3">
                <div className="flex items-center justify-center gap-2">
                  <div className="px-6 py-4 rounded-2xl bg-indigo-600/20 border border-indigo-500/30">
                    <span className="text-3xl font-black font-mono tracking-[0.25em] text-white">{inviteCode}</span>
                  </div>
                </div>
                <p className="text-xs text-gray-500 text-center">Valid for 7 days · One-time use</p>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    onClick={copyCode}
                    className="flex items-center justify-center gap-2 py-2.5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 text-sm transition-colors"
                  >
                    {codeCopied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                    {codeCopied ? 'Copied!' : 'Copy Code'}
                  </button>
                  <button
                    onClick={shareCode}
                    className="flex items-center justify-center gap-2 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-sm font-medium transition-colors"
                  >
                    <Share2 className="w-4 h-4" /> Share
                  </button>
                </div>
                <button
                  onClick={generateCode}
                  className="w-full text-xs text-gray-500 hover:text-gray-300 transition-colors py-1"
                >
                  Generate new code
                </button>
              </div>
            ) : (
              <button
                onClick={generateCode}
                disabled={codeLoading}
                className="w-full py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 disabled:opacity-40 font-semibold text-sm transition-colors flex items-center justify-center gap-2"
              >
                {codeLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Users className="w-4 h-4" />}
                {codeLoading ? 'Generating…' : 'Generate Invite Code'}
              </button>
            )}
          </div>

          {/* What parents see */}
          <div className="space-y-2">
            <p className="text-xs font-medium text-gray-500 uppercase tracking-wider">Parents will see</p>
            {[
              { icon: Zap, label: 'XP earned & level progress' },
              { icon: Flame, label: 'Study streak & daily activity' },
              { icon: BarChart2, label: 'Subject-wise accuracy' },
              { icon: Target, label: 'Weak topics that need attention' },
              { icon: Clock, label: 'Weekly study time' },
            ].map(({ icon: Icon, label }, i) => (
              <div key={i} className="flex items-center gap-3 py-2 px-1 text-sm text-gray-400">
                <Icon className="w-4 h-4 text-indigo-400" /> {label}
              </div>
            ))}
          </div>
        </div>
        </div>
      </div>
    );
  }

  // ── Enter Code Phase (parent) ─────────────────────────────────────────────
  if (phase === 'enter_code') {
    return (
      <div className="h-full text-white flex flex-col">
        <div className="sticky top-0 z-20 border-b border-white/10 px-4 py-3 flex items-center gap-3 shrink-0" style={{ background: 'rgba(8,6,20,0.82)', backdropFilter: 'blur(48px) saturate(200%) brightness(1.04)', WebkitBackdropFilter: 'blur(48px) saturate(200%) brightness(1.04)' }}>
          <button onClick={() => setPhase('student_setup')} className="p-2 rounded-xl hover:bg-white/5">
            <ArrowLeft className="w-5 h-5 text-gray-400" />
          </button>
          <div className="flex-1">
            <h1 className="font-bold text-white">Parent Access</h1>
            <p className="text-xs text-gray-400">Enter the code your child shared with you</p>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto pb-nav">
        <div className="max-w-sm mx-auto px-4 py-12 space-y-8">
          <div className="text-center space-y-2">
            <div className="text-6xl">🔗</div>
            <h2 className="text-xl font-bold">Connect to your child</h2>
            <p className="text-sm text-gray-400">Ask your child to generate an invite code in their Edora app, then enter it below.</p>
          </div>

          <div className="space-y-4">
            <input
              value={enteredCode}
              onChange={(e) => setEnteredCode(e.target.value.toUpperCase().slice(0, 6))}
              placeholder="ENTER CODE"
              className="w-full text-center px-4 py-4 bg-white/5 border border-white/10 rounded-2xl text-2xl font-mono font-black tracking-[0.35em] text-white placeholder:text-gray-700 focus:outline-none focus:border-indigo-500"
            />
            {codeError && (
              <div className="flex items-center gap-2 text-red-400 text-sm">
                <AlertCircle className="w-4 h-4 flex-shrink-0" /> {codeError}
              </div>
            )}
            <button
              onClick={acceptCode}
              disabled={enteredCode.length !== 6 || accepting}
              className="w-full py-4 rounded-2xl bg-indigo-600 hover:bg-indigo-500 disabled:opacity-40 font-bold transition-colors flex items-center justify-center gap-2"
            >
              {accepting ? <Loader2 className="w-5 h-5 animate-spin" /> : <ChevronRight className="w-5 h-5" />}
              {accepting ? 'Connecting…' : 'Connect'}
            </button>
          </div>
        </div>
        </div>
      </div>
    );
  }

  // ── Parent Dashboard ──────────────────────────────────────────────────────
  return (
    <div className="h-full text-white flex flex-col">
      {/* Header */}
      <div className="sticky top-0 z-20 backdrop-blur border-b border-white/5 px-4 py-3 shrink-0">
        <div className="flex items-center gap-3">
          <Link to="/home" className="p-2 rounded-xl hover:bg-white/5">
            <ArrowLeft className="w-5 h-5 text-gray-400" />
          </Link>
          <div className="flex-1">
            <h1 className="font-bold text-white">
              {selectedChild?.child_name ?? 'Child'}'s Dashboard
            </h1>
            <p className="text-xs text-gray-400">Live study progress</p>
          </div>
          <button onClick={() => selectedChild && loadChildStats(selectedChild.child_id)} className="p-2 rounded-xl hover:bg-white/5">
            <RefreshCw className={`w-4 h-4 text-gray-400 ${statsLoading ? 'animate-spin' : ''}`} />
          </button>
        </div>

        {/* Child selector — if multiple children */}
        {childLinks.length > 1 && (
          <div className="flex gap-2 mt-2 overflow-x-auto pb-1 scrollbar-hide">
            {childLinks.map((c) => (
              <button
                key={c.child_id}
                onClick={() => { setSelectedChild(c); loadChildStats(c.child_id); }}
                className={`px-3 py-1 rounded-xl text-xs font-medium whitespace-nowrap transition-colors ${
                  selectedChild?.child_id === c.child_id ? 'bg-indigo-600 text-white' : 'bg-white/5 text-gray-400'
                }`}
              >
                {c.child_name}
              </button>
            ))}
          </div>
        )}
      </div>

      <div className="flex-1 overflow-y-auto pb-nav">
      {statsLoading && !childStats ? (
        <div className="flex justify-center py-20">
          <Loader2 className="w-8 h-8 text-indigo-400 animate-spin" />
        </div>
      ) : !childStats ? (
        <div className="text-center py-20 space-y-3 px-4">
          <div className="text-4xl">📊</div>
          <p className="text-gray-400">No study data yet for {selectedChild?.child_name}.</p>
          <p className="text-sm text-gray-600">Once they start studying, you'll see their progress here.</p>
        </div>
      ) : (
        <div className="max-w-2xl mx-auto px-4 py-5 space-y-5">

          {/* Profile card */}
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            className="p-5 rounded-2xl bg-gradient-to-br from-indigo-900/40 to-purple-900/30 border border-indigo-500/20"
          >
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-2xl bg-indigo-600 flex items-center justify-center text-2xl font-black">
                {childStats.profile.full_name?.[0]?.toUpperCase() ?? '?'}
              </div>
              <div className="flex-1">
                <div className="font-bold text-white text-lg">{childStats.profile.full_name}</div>
                <div className="text-sm text-indigo-300">Level {childStats.profile.level}</div>
                <div className="mt-1.5">
                  <XPBar value={childStats.profile.xp % 1000} max={1000} />
                  <div className="text-[10px] text-gray-500 mt-0.5">{childStats.profile.xp} XP total</div>
                </div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-black text-orange-400">{childStats.profile.streak_count}</div>
                <div className="text-xs text-gray-500">day streak</div>
                <Flame className="w-5 h-5 text-orange-400 mx-auto mt-0.5" />
              </div>
            </div>
          </motion.div>

          {/* This week stats */}
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="grid grid-cols-2 gap-3"
          >
            {[
              { icon: Clock,    value: `${childStats.week.study_minutes}m`, label: 'Study time this week',  color: '#5B6AF5' },
              { icon: Target,   value: `${childStats.week.quiz_accuracy}%`, label: 'Quiz accuracy',          color: '#10B981' },
              { icon: Zap,      value: `+${childStats.week.xp_earned}`,    label: 'XP earned this week',    color: '#F59E0B' },
              { icon: BookOpen, value: `${childStats.week.sessions_completed}`, label: 'Sessions completed', color: '#EC4899' },
            ].map(({ icon: Icon, value, label, color }, i) => (
              <div key={i} className="p-4 rounded-2xl bg-white/5 border border-white/8 space-y-2">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-xl flex items-center justify-center" style={{ background: `${color}20` }}>
                    <Icon className="w-4 h-4" style={{ color }} />
                  </div>
                </div>
                <div className="text-2xl font-black text-white">{value}</div>
                <div className="text-xs text-gray-500">{label}</div>
              </div>
            ))}
          </motion.div>

          {/* Weekly XP chart */}
          {childStats.xp_history.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="p-4 rounded-2xl bg-white/5 border border-white/8 space-y-3"
            >
              <div className="flex items-center gap-2 text-sm font-semibold text-white">
                <TrendingUp className="w-4 h-4 text-indigo-400" /> Weekly XP Trend
              </div>
              <WeeklyChart history={childStats.xp_history} />
            </motion.div>
          )}

          {/* Subject progress */}
          {childStats.subjects.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="p-4 rounded-2xl bg-white/5 border border-white/8 space-y-4"
            >
              <div className="flex items-center gap-2 text-sm font-semibold text-white">
                <BarChart2 className="w-4 h-4 text-indigo-400" /> Subject Progress
              </div>
              <div className="space-y-3">
                {childStats.subjects.map((s) => (
                  <div key={s.subject} className="space-y-1.5">
                    <div className="flex items-center justify-between text-xs">
                      <span style={{ color: SUBJECT_COLORS[s.subject] ?? '#9CA3AF' }} className="font-medium">{s.subject}</span>
                      <span className="text-gray-400">{s.accuracy}% · {s.questions_attempted} questions</span>
                    </div>
                    <XPBar value={s.accuracy} max={100} color={SUBJECT_COLORS[s.subject] ?? '#6B7280'} />
                  </div>
                ))}
              </div>
            </motion.div>
          )}

          {/* Boss fights */}
          {childStats.boss_fights.total > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.35 }}
              className="p-4 rounded-2xl bg-purple-900/20 border border-purple-500/20"
            >
              <div className="flex items-center gap-3">
                <div className="text-3xl">⚔️</div>
                <div className="flex-1">
                  <div className="font-semibold text-white text-sm">Boss Fights</div>
                  <div className="text-xs text-gray-400">
                    {childStats.boss_fights.victories} victories / {childStats.boss_fights.total} fights
                    {childStats.boss_fights.last_boss && ` · Last: ${childStats.boss_fights.last_boss}`}
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-xl font-black text-purple-400">
                    {childStats.boss_fights.total > 0
                      ? `${Math.round((childStats.boss_fights.victories / childStats.boss_fights.total) * 100)}%`
                      : '—'}
                  </div>
                  <div className="text-[10px] text-gray-500">win rate</div>
                </div>
              </div>
            </motion.div>
          )}

          {/* Weak topics alert */}
          {childStats.weak_topics.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
              className="p-4 rounded-2xl bg-red-900/15 border border-red-500/20 space-y-3"
            >
              <div className="flex items-center gap-2 text-sm font-semibold text-red-400">
                <AlertCircle className="w-4 h-4" /> Topics Needing Attention
              </div>
              <div className="space-y-2">
                {childStats.weak_topics.slice(0, 4).map((t, i) => (
                  <div key={i} className="flex items-center justify-between text-xs">
                    <div>
                      <span className="text-white">{t.topic}</span>
                      <span className="text-gray-500 ml-1.5">· {t.subject}</span>
                    </div>
                    <span className="text-red-400 font-semibold">{t.accuracy}%</span>
                  </div>
                ))}
              </div>
            </motion.div>
          )}

          {/* Recent activity */}
          {childStats.recent_activity.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.45 }}
              className="p-4 rounded-2xl bg-white/5 border border-white/8 space-y-3"
            >
              <div className="flex items-center gap-2 text-sm font-semibold text-white">
                <Brain className="w-4 h-4 text-indigo-400" /> Recent Activity
              </div>
              <div className="space-y-2">
                {childStats.recent_activity.slice(0, 6).map((a, i) => (
                  <div key={i} className="flex items-center gap-3 text-xs text-gray-400">
                    <div className="w-1.5 h-1.5 rounded-full bg-indigo-400 flex-shrink-0" />
                    <span className="flex-1">{a.type} · {a.subject}</span>
                    {a.score !== null && <span className="text-white font-medium">{a.score}%</span>}
                    <span className="text-gray-600">{timeAgo(a.created_at)}</span>
                  </div>
                ))}
              </div>
            </motion.div>
          )}

          <div className="pb-8" />
        </div>
      )}
      </div>
    </div>
  );
}

// suppress
void Trophy; void Award; void X;
