// ═══════════════════════════════════════════════════════════════
// Edora — TeacherExportPage
// Formal teacher-ready report: mastery map, error log,
// trajectory, AI assessment + exam prediction.
// ═══════════════════════════════════════════════════════════════

import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ChevronLeft, FileText, TrendingUp, TrendingDown, Minus,
  AlertTriangle, Share2, Eye, X, RefreshCw, Clock,
} from 'lucide-react';
import { Link } from 'react-router-dom';
import { Share } from '@capacitor/share';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';

// ── Types ─────────────────────────────────────────────────────────────────────

interface SubjectMastery {
  mastered: number;
  total: number;
  avg_ef: number;
  weak_topics: string[];
  strong_topics: string[];
}

interface ErrorPattern {
  subject: string;
  pattern: string;
  frequency: number;
}

interface ExportData {
  mastery_by_subject: { [sub: string]: SubjectMastery };
  error_patterns: ErrorPattern[];
  trajectory: {
    direction: 'improving' | 'stable' | 'declining';
    weekly_xp: number[];
    trend: string;
  };
  prediction: { predicted_score: number; predicted_grade: string } | null;
}

interface TeacherExport {
  id: string;
  export_html: string;
  export_data: ExportData;
  generated_at: string;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function timeAgo(isoDate: string): string {
  const diffMs   = Date.now() - new Date(isoDate).getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
  if (diffDays === 0) return 'today';
  if (diffDays === 1) return '1 day ago';
  return `${diffDays} days ago`;
}

async function shareReport(html: string) {
  try {
    await Share.share({
      title: 'Edora Teacher Report',
      text: 'My Edora academic progress report — generated by Novo AI.',
      dialogTitle: 'Share with Teacher',
    });
    return;
  } catch { /* user cancelled or share not available — fall through */ }
  // Fallback: copy HTML to clipboard
  try {
    await navigator.clipboard.writeText(html);
    alert('Report HTML copied to clipboard — paste into an email to share.');
  } catch {
    alert('Could not share. Please take a screenshot or contact support.');
  }
}

// ── Generating steps animation ────────────────────────────────────────────────

const STEPS = [
  'Analysing your mastery data...',
  'Reviewing error patterns...',
  'Novo is writing your assessment...',
  'Formatting your report...',
];

function GeneratingSteps() {
  const [step, setStep] = useState(0);

  useEffect(() => {
    if (step >= STEPS.length - 1) return;
    const t = setTimeout(() => setStep(s => s + 1), 2000);
    return () => clearTimeout(t);
  }, [step]);

  return (
    <div className="rounded-3xl p-5"
      style={{ background: 'rgba(15,20,45,0.75)', border: '1px solid rgba(255,255,255,0.07)' }}>
      <div className="flex items-center gap-3 mb-5">
        <div className="w-10 h-10 rounded-2xl flex items-center justify-center"
          style={{ background: 'linear-gradient(135deg, #5B6AF5, #8B5CF6)' }}>
          <FileText size={18} className="text-white" />
        </div>
        <div>
          <p className="font-semibold text-white text-sm">Building your report</p>
          <p className="text-[11px]" style={{ color: 'rgba(255,255,255,0.5)' }}>This takes ~15 seconds</p>
        </div>
      </div>

      <div className="flex flex-col gap-2">
        {STEPS.map((label, i) => (
          <motion.div key={i}
            initial={{ opacity: 0.25 }}
            animate={{ opacity: i <= step ? 1 : 0.25 }}
            className="flex items-center gap-2.5">
            <motion.div
              className="w-4 h-4 rounded-full border-2 flex items-center justify-center shrink-0"
              animate={{
                borderColor: i < step ? '#10B981' : i === step ? '#5B6AF5' : 'rgba(255,255,255,0.15)',
                background:  i < step ? '#10B981' : 'transparent',
              }}>
              {i < step && (
                <svg width="8" height="8" viewBox="0 0 8 8" fill="none">
                  <path d="M1.5 4L3 5.5L6.5 2" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
                </svg>
              )}
              {i === step && (
                <motion.div className="w-1.5 h-1.5 rounded-full"
                  style={{ background: '#5B6AF5' }}
                  animate={{ scale: [1, 1.4, 1] }}
                  transition={{ duration: 0.8, repeat: Infinity }} />
              )}
            </motion.div>
            <span className="text-xs" style={{ color: i === step ? '#fff' : 'rgba(255,255,255,0.5)', fontWeight: i === step ? 600 : 400 }}>
              {label}
            </span>
          </motion.div>
        ))}
      </div>
    </div>
  );
}

// ── Subject mastery bar ───────────────────────────────────────────────────────

function MasteryBar({ subject, mastered, total }: { subject: string; mastered: number; total: number }) {
  const pct   = total > 0 ? Math.round((mastered / total) * 100) : 0;
  const color = pct >= 70 ? '#10B981' : pct >= 40 ? '#F59E0B' : '#EF4444';

  return (
    <div>
      <div className="flex justify-between items-center mb-1">
        <span className="text-xs font-medium text-white capitalize">{subject}</span>
        <span className="text-[10px]" style={{ color: 'rgba(255,255,255,0.5)' }}>{mastered}/{total} · {pct}%</span>
      </div>
      <div className="h-2 rounded-full overflow-hidden" style={{ background: 'rgba(255,255,255,0.08)' }}>
        <motion.div
          className="h-full rounded-full"
          style={{ background: color }}
          initial={{ width: 0 }}
          animate={{ width: `${pct}%` }}
          transition={{ duration: 0.9, ease: 'easeOut' }} />
      </div>
    </div>
  );
}

// ── Trajectory badge ──────────────────────────────────────────────────────────

function TrajectoryBadge({ direction }: { direction: 'improving' | 'stable' | 'declining' }) {
  const map = {
    improving: { icon: TrendingUp,   label: 'Improving', bg: 'rgba(16,185,129,0.12)',  color: '#34D399' },
    stable:    { icon: Minus,        label: 'Stable',    bg: 'rgba(245,158,11,0.12)',  color: '#FBBF24' },
    declining: { icon: TrendingDown, label: 'Declining', bg: 'rgba(239,68,68,0.12)',   color: '#F87171' },
  };
  const { icon: Icon, label, bg, color } = map[direction];
  return (
    <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold"
      style={{ background: bg, color }}>
      <Icon size={13} /> {label}
    </span>
  );
}

// ── Skeleton ──────────────────────────────────────────────────────────────────

function Skeleton({ className }: { className?: string }) {
  return <div className={`animate-pulse rounded-xl ${className ?? ''}`} style={{ background: 'rgba(255,255,255,0.06)' }} />;
}

// ── Main component ────────────────────────────────────────────────────────────

export default function TeacherExportPage() {
  const { user } = useAuth();

  const [exportData, setExportData] = useState<TeacherExport | null>(null);
  const [generating, setGenerating] = useState(false);
  const [showModal,  setShowModal]  = useState(false);
  const [loading,    setLoading]    = useState(true);

  // ── Load latest export ──────────────────────────────────────────────────────
  const loadExport = useCallback(async () => {
    if (!user) return;
    try {
      const { data } = await supabase.functions.invoke('teacher-export', {
        body: { action: 'get_latest' },
      });
      if (data?.export) setExportData(data.export as TeacherExport);
    } catch (e) {
      console.error('[TeacherExport] load:', e);
    } finally {
      setLoading(false);
    }
  }, [user]);

  useEffect(() => { loadExport(); }, [loadExport]);

  // ── Generate ─────────────────────────────────────────────────────────────────
  async function handleGenerate() {
    setGenerating(true);
    try {
      const { data } = await supabase.functions.invoke('teacher-export', {
        body: { action: 'generate' },
      });
      if (data?.export) {
        setExportData(data.export as TeacherExport);
      }
    } catch (e) {
      console.error('[TeacherExport] generate:', e);
    } finally {
      setGenerating(false);
    }
  }

  const ed = exportData?.export_data;
  const masteryEntries = Object.entries(ed?.mastery_by_subject ?? {});

  return (
    <div className="flex flex-col h-full bg-gradient-page">

      {/* Header */}
      <div className="px-4 py-3 flex items-center gap-3 shrink-0 sticky top-0 z-10"
        style={{ background: 'rgba(10,12,28,0.85)', borderBottom: '1px solid rgba(255,255,255,0.06)', backdropFilter: 'blur(12px)' }}>
        <Link to="/profile">
          <button aria-label="Go back" className="w-8 h-8 flex items-center justify-center rounded-xl text-white transition-colors"
            style={{ background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.1)', WebkitTapHighlightColor: 'transparent' }}>
            <ChevronLeft size={18} />
          </button>
        </Link>
        <div className="w-10 h-10 rounded-2xl flex items-center justify-center shrink-0"
          style={{ background: 'linear-gradient(135deg, #5B6AF5, #8B5CF6)' }}>
          <FileText size={20} className="text-white" />
        </div>
        <div className="flex-1">
          <h2 className="font-heading font-bold text-white text-sm">Teacher Export</h2>
          <p className="text-xs" style={{ color: 'rgba(255,255,255,0.5)' }}>Professional progress report</p>
        </div>
      </div>

      <div className="flex-1 native-scroll pb-nav px-4 py-4 flex flex-col gap-4">

        {/* ── Intro card ────────────────────────────────────────────────── */}
        <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
          className="rounded-3xl p-4"
          style={{ background: 'rgba(15,20,45,0.75)', border: '1px solid rgba(255,255,255,0.07)' }}>
          <p className="font-semibold text-white text-sm mb-2">Professional report for your teacher</p>
          <div className="flex flex-wrap gap-1.5 mb-3">
            {['Mastery Map', 'Error Log', 'Learning Trajectory', 'AI Assessment', 'Exam Prediction'].map(f => (
              <span key={f}
                className="text-[10px] font-medium px-2.5 py-1 rounded-full"
                style={{ border: '1px solid rgba(255,255,255,0.1)', color: 'rgba(255,255,255,0.6)' }}>
                {f}
              </span>
            ))}
          </div>
          <p className="text-[11px] flex items-center gap-1" style={{ color: 'rgba(255,255,255,0.5)' }}>
            <Clock size={11} /> This takes ~15 seconds to generate
          </p>
        </motion.div>

        {/* ── Generating / No export / Export exists ───────────────────── */}
        {loading ? (
          <div className="flex flex-col gap-3">
            <Skeleton className="h-36" />
            <Skeleton className="h-24" />
          </div>
        ) : generating ? (
          <GeneratingSteps />
        ) : !exportData ? (
          /* No export yet */
          <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.06 }}>
            <button
              onClick={handleGenerate}
              className="w-full py-4 rounded-2xl text-white font-semibold text-base flex items-center justify-center gap-2"
              style={{ background: 'linear-gradient(135deg, #5B6AF5, #8B5CF6)' }}>
              <FileText size={18} /> Generate Teacher Report
            </button>
          </motion.div>
        ) : (
          /* Export exists */
          <>
            {/* Status bar */}
            <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}
              className="flex items-center gap-2">
              <span className="flex items-center gap-1 text-[11px] rounded-full px-3 py-1"
                style={{ background: 'rgba(15,20,45,0.75)', border: '1px solid rgba(255,255,255,0.08)', color: 'rgba(255,255,255,0.5)' }}>
                <Clock size={10} /> Generated {timeAgo(exportData.generated_at)}
              </span>
              <button
                onClick={handleGenerate}
                className="flex items-center gap-1 text-[11px] rounded-full px-3 py-1 transition-colors"
                style={{ background: 'rgba(15,20,45,0.75)', border: '1px solid rgba(255,255,255,0.08)', color: 'rgba(255,255,255,0.5)' }}>
                <RefreshCw size={11} /> Regenerate
              </button>
            </motion.div>

            {/* ── Mastery summary ──────────────────────────────────────── */}
            {masteryEntries.length > 0 && (
              <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.08 }}
                className="rounded-3xl overflow-hidden"
                style={{ background: 'rgba(15,20,45,0.75)', border: '1px solid rgba(255,255,255,0.07)' }}>
                <div className="px-4 pt-4 pb-2" style={{ borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
                  <p className="font-semibold text-white text-sm">Mastery by Subject</p>
                </div>
                <div className="px-4 py-4 flex flex-col gap-3">
                  {masteryEntries.map(([sub, m]) => (
                    <MasteryBar key={sub} subject={sub} mastered={m.mastered} total={m.total} />
                  ))}
                </div>
              </motion.div>
            )}

            {/* ── Trajectory + Error patterns ──────────────────────────── */}
            <div className="grid grid-cols-2 gap-3">
              {ed?.trajectory && (
                <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.10 }}
                  className="rounded-3xl p-4"
                  style={{ background: 'rgba(15,20,45,0.75)', border: '1px solid rgba(255,255,255,0.07)' }}>
                  <p className="text-[11px] mb-2 font-medium" style={{ color: 'rgba(255,255,255,0.5)' }}>Trajectory</p>
                  <TrajectoryBadge direction={ed.trajectory.direction} />
                  {ed.trajectory.trend && (
                    <p className="text-[10px] mt-2 line-clamp-2" style={{ color: 'rgba(255,255,255,0.5)' }}>
                      {ed.trajectory.trend}
                    </p>
                  )}
                </motion.div>
              )}

              {ed?.error_patterns && (
                <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.12 }}
                  className="rounded-3xl p-4"
                  style={{ background: 'rgba(15,20,45,0.75)', border: '1px solid rgba(255,255,255,0.07)' }}>
                  <p className="text-[11px] mb-2 font-medium" style={{ color: 'rgba(255,255,255,0.5)' }}>Error Patterns</p>
                  <div className="flex items-center gap-2">
                    <div className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0"
                      style={{ background: 'rgba(236,72,153,0.12)', border: '1px solid rgba(236,72,153,0.25)' }}>
                      <AlertTriangle size={16} style={{ color: '#F472B6' }} />
                    </div>
                    <div>
                      <p className="font-heading font-bold text-white text-lg leading-none">
                        {ed.error_patterns.length}
                      </p>
                      <p className="text-[10px]" style={{ color: 'rgba(255,255,255,0.5)' }}>patterns found</p>
                    </div>
                  </div>
                </motion.div>
              )}
            </div>

            {/* ── Exam prediction ──────────────────────────────────────── */}
            {ed?.prediction && (
              <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.14 }}
                className="rounded-3xl p-4"
                style={{ background: 'rgba(15,20,45,0.75)', border: '1px solid rgba(255,255,255,0.07)' }}>
                <p className="font-semibold text-white text-sm mb-1">Exam Prediction</p>
                <div className="flex items-center gap-4">
                  <div>
                    <p className="font-heading font-bold text-3xl leading-none" style={{ color: '#8B9BFA' }}>
                      {ed.prediction.predicted_score}%
                    </p>
                    <p className="text-xs mt-0.5" style={{ color: 'rgba(255,255,255,0.5)' }}>predicted score</p>
                  </div>
                  <div className="h-10 w-px" style={{ background: 'rgba(255,255,255,0.08)' }} />
                  <div>
                    <p className="font-heading font-bold text-3xl text-white leading-none">
                      {ed.prediction.predicted_grade}
                    </p>
                    <p className="text-xs mt-0.5" style={{ color: 'rgba(255,255,255,0.5)' }}>predicted grade</p>
                  </div>
                </div>
              </motion.div>
            )}

            {/* ── CTA buttons ──────────────────────────────────────────── */}
            <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.16 }}
              className="flex gap-3">
              <button
                onClick={() => setShowModal(true)}
                className="flex-1 py-3.5 rounded-2xl text-sm font-semibold border-2 flex items-center justify-center gap-2 transition-colors"
                style={{ borderColor: '#5B6AF5', color: '#8B9BFA', background: 'rgba(91,106,245,0.1)' }}>
                <Eye size={15} /> View Full Report
              </button>
              <button
                onClick={() => shareReport(exportData.export_html)}
                className="flex-1 py-3.5 rounded-2xl text-white text-sm font-semibold flex items-center justify-center gap-2"
                style={{ background: 'linear-gradient(135deg, #5B6AF5, #8B5CF6)' }}>
                <Share2 size={15} /> Share
              </button>
            </motion.div>
          </>
        )}

        <div className="h-6" />
      </div>

      {/* ── Full Report Modal ─────────────────────────────────────────────── */}
      <AnimatePresence>
        {showModal && exportData && (
          <motion.div
            className="fixed inset-0 z-50 flex flex-col"
            style={{ background: '#0A0F25' }}
            initial={{ y: '100%' }}
            animate={{ y: 0 }}
            exit={{ y: '100%' }}
            transition={{ type: 'spring', damping: 30, stiffness: 280 }}>

            {/* Modal header */}
            <div className="flex items-center gap-3 px-4 py-3 shrink-0"
              style={{ borderBottom: '1px solid rgba(255,255,255,0.06)', background: 'rgba(10,12,28,0.85)', backdropFilter: 'blur(12px)' }}>
              <div className="w-8 h-8 rounded-xl flex items-center justify-center shrink-0"
                style={{ background: 'linear-gradient(135deg, #5B6AF5, #8B5CF6)' }}>
                <FileText size={15} className="text-white" />
              </div>
              <div className="flex-1">
                <p className="font-semibold text-white text-sm">Teacher Export</p>
                <p className="text-[10px]" style={{ color: 'rgba(255,255,255,0.5)' }}>Generated {timeAgo(exportData.generated_at)}</p>
              </div>
              <button
                onClick={() => setShowModal(false)}
                className="w-8 h-8 flex items-center justify-center rounded-xl text-white"
                style={{ background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.1)' }}>
                <X size={16} />
              </button>
            </div>

            {/* iframe */}
            <div className="flex-1 overflow-hidden">
              <iframe
                srcDoc={exportData.export_html}
                style={{ width: '100%', height: '100%', border: 'none' }}
                title="Teacher Export"
              />
            </div>

            {/* Modal footer */}
            <div className="px-4 py-4 shrink-0" style={{ borderTop: '1px solid rgba(255,255,255,0.06)' }}>
              <button
                onClick={() => shareReport(exportData.export_html)}
                className="w-full py-3 rounded-2xl text-white font-semibold text-sm flex items-center justify-center gap-2"
                style={{ background: 'linear-gradient(135deg, #5B6AF5, #8B5CF6)' }}>
                <Share2 size={16} /> Share with Teacher
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
