-- Extended PYQ seed — Part 2: JEE_ADV (Physics 23, Chemistry 23, Maths 22) + NEET Physics 47

INSERT INTO public.pyq_content
  (exam, year, subject, chapter, question_text, solution_text, options, correct_option, question_type, difficulty, marks)
VALUES

-- ── JEE ADVANCED · PHYSICS ──────────────────────────────────────────────────

('JEE_ADV', 2023, 'Physics', 'Kinematics',
 'A particle moves along x-axis with velocity v = 3t² − 6t. The particle is momentarily at rest at t =',
 'v = 0: 3t² − 6t = 0 → 3t(t−2) = 0 → t = 0 or t = 2 s.',
 '[{"label":"A","text":"t = 1 s only","correct":false},{"label":"B","text":"t = 0 and t = 2 s","correct":true},{"label":"C","text":"t = 2 s only","correct":false},{"label":"D","text":"t = 3 s","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2022, 'Physics', 'Work and Energy',
 'A spring of spring constant k is compressed by distance x. The potential energy stored is:',
 'PE = ½kx². For elastic potential energy of compressed/stretched spring.',
 '[{"label":"A","text":"kx","correct":false},{"label":"B","text":"kx²","correct":false},{"label":"C","text":"½kx²","correct":true},{"label":"D","text":"2kx²","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_ADV', 2023, 'Physics', 'Centre of Mass',
 'In a system of two particles, if one particle has mass 3m at position x=0 and another mass m at x=4, the centre of mass is at:',
 'x_cm = (m₁x₁ + m₂x₂)/(m₁+m₂) = (3m×0 + m×4)/(3m+m) = 4m/4m = 1.',
 '[{"label":"A","text":"x = 2","correct":false},{"label":"B","text":"x = 1","correct":true},{"label":"C","text":"x = 3","correct":false},{"label":"D","text":"x = 1.5","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2021, 'Physics', 'Rotational Motion',
 'A ring and a disc of same mass and radius roll down an incline. Which reaches the bottom first?',
 'Acceleration a = g sinθ/(1 + I/MR²). Disc: I = MR²/2, a = 2g sinθ/3. Ring: I = MR², a = g sinθ/2. Disc has higher acceleration → reaches first.',
 '[{"label":"A","text":"Ring","correct":false},{"label":"B","text":"Disc","correct":true},{"label":"C","text":"Both simultaneously","correct":false},{"label":"D","text":"Depends on incline angle","correct":false}]',
 'B', 'mcq', 'hard', 4),

('JEE_ADV', 2023, 'Physics', 'Gravitation',
 'The orbital speed of a satellite of mass m in a circular orbit of radius r around Earth (mass M) is:',
 'Centripetal force = gravitational force: mv²/r = GMm/r². So v = √(GM/r).',
 '[{"label":"A","text":"√(GM/r)","correct":true},{"label":"B","text":"√(2GM/r)","correct":false},{"label":"C","text":"GM/r","correct":false},{"label":"D","text":"√(GMr)","correct":false}]',
 'A', 'mcq', 'medium', 4),

('JEE_ADV', 2022, 'Physics', 'Fluid Mechanics',
 'A body floats in water with 3/4 of its volume submerged. The density of the body is:',
 'Buoyancy: ρ_body × V × g = ρ_water × (3V/4) × g. ρ_body = (3/4) × 1000 = 750 kg/m³.',
 '[{"label":"A","text":"1000 kg/m³","correct":false},{"label":"B","text":"500 kg/m³","correct":false},{"label":"C","text":"750 kg/m³","correct":true},{"label":"D","text":"250 kg/m³","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_ADV', 2021, 'Physics', 'Electrostatics',
 'The electric potential at the centre of a uniformly charged ring of charge Q and radius R is:',
 'All charge on ring is at distance R from centre. V = kQ/R = Q/(4πε₀R).',
 '[{"label":"A","text":"Zero","correct":false},{"label":"B","text":"kQ/R²","correct":false},{"label":"C","text":"kQ/R","correct":true},{"label":"D","text":"kQ/2R","correct":false}]',
 'C', 'mcq', 'hard', 4),

('JEE_ADV', 2023, 'Physics', 'Current Electricity',
 'Kirchhoff''s voltage law (KVL) is based on:',
 'KVL states sum of EMFs = sum of potential drops in a closed loop. Based on conservation of energy.',
 '[{"label":"A","text":"Conservation of charge","correct":false},{"label":"B","text":"Conservation of energy","correct":true},{"label":"C","text":"Conservation of momentum","correct":false},{"label":"D","text":"Ohm''s law","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_ADV', 2022, 'Physics', 'Capacitance',
 'Two capacitors C₁ = 4 μF and C₂ = 6 μF are connected in series. Their equivalent capacitance is:',
 '1/C = 1/4 + 1/6 = 3/12 + 2/12 = 5/12. C = 12/5 = 2.4 μF.',
 '[{"label":"A","text":"10 μF","correct":false},{"label":"B","text":"2.4 μF","correct":true},{"label":"C","text":"5 μF","correct":false},{"label":"D","text":"1.2 μF","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2021, 'Physics', 'Electromagnetic Induction',
 'Lenz''s law is a consequence of:',
 'Lenz''s law: induced current opposes the change causing it. This is a manifestation of conservation of energy.',
 '[{"label":"A","text":"Faraday''s flux rule","correct":false},{"label":"B","text":"Conservation of energy","correct":true},{"label":"C","text":"Ampere''s law","correct":false},{"label":"D","text":"Biot-Savart law","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2022, 'Physics', 'Wave Optics',
 'In a double-slit experiment with slit separation d, screen distance D, the 3rd bright fringe is at distance from centre:',
 'Position of nth bright fringe: y_n = nλD/d. For n=3: y₃ = 3λD/d.',
 '[{"label":"A","text":"λD/d","correct":false},{"label":"B","text":"2λD/d","correct":false},{"label":"C","text":"3λD/d","correct":true},{"label":"D","text":"4λD/d","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_ADV', 2023, 'Physics', 'Modern Physics',
 'The energy of a photon of wavelength 500 nm is approximately (h = 6.6×10⁻³⁴ J·s, c = 3×10⁸ m/s):',
 'E = hc/λ = (6.6×10⁻³⁴ × 3×10⁸)/(500×10⁻⁹) = 19.8×10⁻²⁶/5×10⁻⁷ = 3.96×10⁻¹⁹ J ≈ 4×10⁻¹⁹ J ≈ 2.5 eV.',
 '[{"label":"A","text":"≈ 1 eV","correct":false},{"label":"B","text":"≈ 2.5 eV","correct":true},{"label":"C","text":"≈ 5 eV","correct":false},{"label":"D","text":"≈ 10 eV","correct":false}]',
 'B', 'mcq', 'hard', 4),

('JEE_ADV', 2021, 'Physics', 'Thermodynamics',
 'For an adiabatic process, which relation holds (γ = Cp/Cv)?',
 'For adiabatic process: TV^(γ−1) = constant, PV^γ = constant. No heat exchange with surroundings.',
 '[{"label":"A","text":"PV = constant","correct":false},{"label":"B","text":"PV^γ = constant","correct":true},{"label":"C","text":"P/V = constant","correct":false},{"label":"D","text":"PV^(1/γ) = constant","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2022, 'Physics', 'Waves',
 'Standing waves are produced by superposition of two waves with:',
 'Standing waves form when two waves of same frequency and amplitude travel in opposite directions.',
 '[{"label":"A","text":"Same frequency, same direction","correct":false},{"label":"B","text":"Different frequencies, any direction","correct":false},{"label":"C","text":"Same frequency and amplitude, opposite directions","correct":true},{"label":"D","text":"Different amplitudes, same direction","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_ADV', 2023, 'Physics', 'Optics',
 'A concave mirror of focal length 20 cm has an object at 30 cm. The image distance is:',
 'Mirror formula: 1/v + 1/u = 1/f. u=−30, f=−20 (concave). 1/v = 1/(−20) − 1/(−30) = −3/60 + 2/60 = −1/60. v = −60 cm. Real, inverted image at 60 cm.',
 '[{"label":"A","text":"−60 cm","correct":true},{"label":"B","text":"60 cm","correct":false},{"label":"C","text":"−30 cm","correct":false},{"label":"D","text":"−120 cm","correct":false}]',
 'A', 'mcq', 'hard', 4),

('JEE_ADV', 2021, 'Physics', 'Nuclear Physics',
 'The binding energy per nucleon is maximum for:',
 'Iron-56 (⁵⁶Fe) has the highest binding energy per nucleon (~8.8 MeV), making it the most stable nucleus.',
 '[{"label":"A","text":"Hydrogen","correct":false},{"label":"B","text":"Iron-56","correct":true},{"label":"C","text":"Uranium-235","correct":false},{"label":"D","text":"Helium-4","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2022, 'Physics', 'Semiconductor Devices',
 'A transistor in common-emitter configuration has current gain β = 50. If base current is 20 μA, the collector current is:',
 'β = Ic/Ib. Ic = β × Ib = 50 × 20 μA = 1000 μA = 1 mA.',
 '[{"label":"A","text":"0.4 mA","correct":false},{"label":"B","text":"1 mA","correct":true},{"label":"C","text":"2.5 mA","correct":false},{"label":"D","text":"50 μA","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2023, 'Physics', 'SHM',
 'In SHM, the restoring force is maximum at:',
 'F = −kx. Restoring force is maximum when displacement x is maximum, i.e., at the extreme positions (x = ±A).',
 '[{"label":"A","text":"Mean position","correct":false},{"label":"B","text":"Quarter amplitude","correct":false},{"label":"C","text":"Extreme positions","correct":true},{"label":"D","text":"Same at all positions","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_ADV', 2021, 'Physics', 'Ray Optics',
 'If the speed of light in a medium is 2×10⁸ m/s, the refractive index of the medium is (c = 3×10⁸ m/s):',
 'n = c/v = (3×10⁸)/(2×10⁸) = 1.5.',
 '[{"label":"A","text":"1.0","correct":false},{"label":"B","text":"1.5","correct":true},{"label":"C","text":"2.0","correct":false},{"label":"D","text":"0.67","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_ADV', 2022, 'Physics', 'Laws of Motion',
 'A block on a rough surface has coefficient of static friction μ_s = 0.3. The maximum static friction force on a 5 kg block is (g = 10 m/s²):',
 'f_s(max) = μ_s × N = μ_s × mg = 0.3 × 5 × 10 = 15 N.',
 '[{"label":"A","text":"1.5 N","correct":false},{"label":"B","text":"15 N","correct":true},{"label":"C","text":"150 N","correct":false},{"label":"D","text":"3 N","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_ADV', 2023, 'Physics', 'Magnetism',
 'The Biot-Savart law gives the magnetic field due to:',
 'Biot-Savart law: dB = (μ₀/4π) × (I dl × r̂)/r². Gives field contribution from a current element.',
 '[{"label":"A","text":"A magnetic monopole","correct":false},{"label":"B","text":"A current element","correct":true},{"label":"C","text":"A moving charge only","correct":false},{"label":"D","text":"A changing electric field","correct":false}]',
 'B', 'mcq', 'medium', 4),

-- ── JEE ADVANCED · CHEMISTRY ────────────────────────────────────────────────

('JEE_ADV', 2023, 'Chemistry', 'Chemical Bonding',
 'The shape of PCl₅ molecule is:',
 'P has 5 bonding pairs, no lone pairs in PCl₅. VSEPR: trigonal bipyramidal geometry.',
 '[{"label":"A","text":"Tetrahedral","correct":false},{"label":"B","text":"Octahedral","correct":false},{"label":"C","text":"Trigonal bipyramidal","correct":true},{"label":"D","text":"Square planar","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_ADV', 2022, 'Chemistry', 'Chemical Equilibrium',
 'For the reaction A ⇌ B + C, if the pressure is increased, the equilibrium shifts:',
 'Increasing pressure favours side with fewer moles of gas. Left has 1 mol, right has 2 mol. Equilibrium shifts left.',
 '[{"label":"A","text":"To the right","correct":false},{"label":"B","text":"To the left","correct":true},{"label":"C","text":"No change","correct":false},{"label":"D","text":"Depends on temperature","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2021, 'Chemistry', 'Electrochemistry',
 'The Nernst equation for electrode potential at temperature T is:',
 'Nernst equation: E = E° − (RT/nF) ln Q = E° − (0.0592/n) log Q at 25°C.',
 '[{"label":"A","text":"E = E° + (RT/nF) ln Q","correct":false},{"label":"B","text":"E = E° − (RT/nF) ln Q","correct":true},{"label":"C","text":"E = E° × (RT/nF)","correct":false},{"label":"D","text":"E = nFE°/RT","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2023, 'Chemistry', 'Organic Chemistry - Isomerism',
 'Optical isomers differ in:',
 'Optical isomers (enantiomers) are non-superimposable mirror images. They have identical physical properties but rotate plane-polarised light in opposite directions.',
 '[{"label":"A","text":"Molecular formula","correct":false},{"label":"B","text":"Connectivity of atoms","correct":false},{"label":"C","text":"Arrangement of groups in space about a chiral centre","correct":true},{"label":"D","text":"Number of bonds","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_ADV', 2022, 'Chemistry', 'Thermodynamics',
 'The standard enthalpy of combustion of carbon is −393.5 kJ/mol. This means:',
 'ΔH_combustion = −393.5 kJ/mol means 393.5 kJ is released when 1 mol of C burns completely to form CO₂.',
 '[{"label":"A","text":"393.5 kJ is absorbed per mol of CO₂ formed","correct":false},{"label":"B","text":"393.5 kJ is released per mol of C burned","correct":true},{"label":"C","text":"Carbon is unstable","correct":false},{"label":"D","text":"Reaction is endothermic","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_ADV', 2021, 'Chemistry', 'Coordination Compounds',
 'The EAN (effective atomic number) rule predicts stability of:',
 'EAN rule (Sidgwick): stable complexes have the central metal atom with EAN = nearest noble gas (36, 54, 86). Used to predict coordination number.',
 '[{"label":"A","text":"Ionic compounds","correct":false},{"label":"B","text":"Coordination complexes","correct":true},{"label":"C","text":"Covalent molecules","correct":false},{"label":"D","text":"Interstitial compounds","correct":false}]',
 'B', 'mcq', 'hard', 4),

('JEE_ADV', 2023, 'Chemistry', 'Atomic Structure',
 'According to Heisenberg''s uncertainty principle, it is impossible to simultaneously determine exactly:',
 'Δx × Δp ≥ ℏ/2. Position and momentum cannot both be precisely known simultaneously.',
 '[{"label":"A","text":"Mass and charge","correct":false},{"label":"B","text":"Position and momentum","correct":true},{"label":"C","text":"Energy and charge","correct":false},{"label":"D","text":"Spin and mass","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_ADV', 2022, 'Chemistry', 'Chemical Kinetics',
 'The Arrhenius equation relates rate constant to temperature as:',
 'k = Ae^(−Ea/RT). As temperature increases, k increases exponentially. Ea is activation energy, A is frequency factor.',
 '[{"label":"A","text":"k = A + Ea/RT","correct":false},{"label":"B","text":"k = Ae^(−Ea/RT)","correct":true},{"label":"C","text":"k = Ae^(Ea/RT)","correct":false},{"label":"D","text":"k = RT/Ea","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2021, 'Chemistry', 'p-Block Elements',
 'XeF₄ has which geometry?',
 'Xe in XeF₄: 4 bonding + 2 lone pairs = 6 electron pairs (octahedral). 2 lone pairs occupy axial positions → square planar geometry.',
 '[{"label":"A","text":"Tetrahedral","correct":false},{"label":"B","text":"Octahedral","correct":false},{"label":"C","text":"Square planar","correct":true},{"label":"D","text":"See-saw","correct":false}]',
 'C', 'mcq', 'hard', 4),

('JEE_ADV', 2022, 'Chemistry', 'Organic - Named Reactions',
 'The Sandmeyer reaction involves replacement of diazonium group by:',
 'Sandmeyer reaction: ArN₂⁺ + CuX → ArX + N₂. Replaces diazonium (−N₂⁺) with halide (Cl, Br, CN) using Cu salts.',
 '[{"label":"A","text":"OH group","correct":false},{"label":"B","text":"Halide (Cl, Br, CN) using Cu salts","correct":true},{"label":"C","text":"Nitro group","correct":false},{"label":"D","text":"Amino group","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2023, 'Chemistry', 'Solutions',
 'The osmotic pressure of a dilute solution is given by van''t Hoff equation:',
 'π = iCRT = iMRT where i = van''t Hoff factor, C = molar concentration, R = gas constant, T = temperature (K).',
 '[{"label":"A","text":"π = nRT/V","correct":false},{"label":"B","text":"π = iCRT","correct":true},{"label":"C","text":"π = C/RT","correct":false},{"label":"D","text":"π = RT/iC","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2021, 'Chemistry', 'Organic - Polymers',
 'Bakelite is an example of:',
 'Bakelite = phenol + formaldehyde → cross-linked thermosetting polymer. Once set, cannot be remelted.',
 '[{"label":"A","text":"Thermoplastic polymer","correct":false},{"label":"B","text":"Elastomer","correct":false},{"label":"C","text":"Thermosetting polymer","correct":true},{"label":"D","text":"Biodegradable polymer","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_ADV', 2022, 'Chemistry', 'Redox and Electrochemistry',
 'In the cell Cu|Cu²⁺(0.1M)||Ag⁺(1M)|Ag, if E°cell = 0.46 V, the cell potential at 25°C using Nernst equation is:',
 'E = E° − (0.0592/2) log([Cu²⁺]/[Ag⁺]²) = 0.46 − (0.0296) × log(0.1/1) = 0.46 − 0.0296×(−1) = 0.46 + 0.03 ≈ 0.49 V.',
 '[{"label":"A","text":"0.46 V","correct":false},{"label":"B","text":"0.43 V","correct":false},{"label":"C","text":"≈ 0.49 V","correct":true},{"label":"D","text":"0.40 V","correct":false}]',
 'C', 'mcq', 'hard', 4),

('JEE_ADV', 2023, 'Chemistry', 'Biomolecules',
 'Which linkage joins two monosaccharides in a disaccharide?',
 'Glycosidic bond (a type of acetal linkage) joins two monosaccharides in disaccharides via condensation (loss of H₂O).',
 '[{"label":"A","text":"Peptide bond","correct":false},{"label":"B","text":"Phosphodiester bond","correct":false},{"label":"C","text":"Glycosidic bond","correct":true},{"label":"D","text":"Hydrogen bond","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_ADV', 2021, 'Chemistry', 'Nuclear Chemistry',
 'Which type of radiation is most penetrating?',
 'Penetrating power: α < β < γ. Gamma rays are electromagnetic waves with no charge or mass, most penetrating. α stopped by paper, β by few mm Al, γ needs cm of Pb.',
 '[{"label":"A","text":"Alpha","correct":false},{"label":"B","text":"Beta","correct":false},{"label":"C","text":"Gamma","correct":true},{"label":"D","text":"Proton","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_ADV', 2022, 'Chemistry', 'Isomerism',
 'Geometrical isomerism is possible in:',
 '2-butene (CH₃CH=CHCH₃) has restricted rotation around C=C double bond with different groups on each carbon → cis/trans isomers.',
 '[{"label":"A","text":"Propene","correct":false},{"label":"B","text":"2-butene","correct":true},{"label":"C","text":"Ethylene","correct":false},{"label":"D","text":"Propyne","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2023, 'Chemistry', 'Acids Bases',
 'A buffer solution contains equal moles of a weak acid and its salt. Its pH equals:',
 'Henderson-Hasselbalch: pH = pKa + log([A⁻]/[HA]). When [A⁻] = [HA], log(1) = 0. pH = pKa.',
 '[{"label":"A","text":"7","correct":false},{"label":"B","text":"pKa","correct":true},{"label":"C","text":"pKa + 1","correct":false},{"label":"D","text":"pKb","correct":false}]',
 'B', 'mcq', 'medium', 4),

-- ── JEE ADVANCED · MATHEMATICS ──────────────────────────────────────────────

('JEE_ADV', 2023, 'Maths', 'Complex Numbers',
 'The argument of the complex number −1 + i√3 is:',
 'Re = −1, Im = √3. Lies in 2nd quadrant. tan(θ) = √3/(−1), reference angle = 60°. arg = π − π/3 = 2π/3.',
 '[{"label":"A","text":"π/3","correct":false},{"label":"B","text":"2π/3","correct":true},{"label":"C","text":"−2π/3","correct":false},{"label":"D","text":"π/6","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2022, 'Maths', 'Quadratic Equations',
 'If α and β are roots of 2x² − 3x + 1 = 0, the value of α² + β² is:',
 'α+β = 3/2, αβ = 1/2. α²+β² = (α+β)² − 2αβ = 9/4 − 1 = 5/4.',
 '[{"label":"A","text":"9/4","correct":false},{"label":"B","text":"5/4","correct":true},{"label":"C","text":"1/4","correct":false},{"label":"D","text":"7/4","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_ADV', 2021, 'Maths', 'Matrices',
 'If A = [[1,2],[3,4]], then det(A) is:',
 'det(A) = 1×4 − 2×3 = 4 − 6 = −2.',
 '[{"label":"A","text":"2","correct":false},{"label":"B","text":"−2","correct":true},{"label":"C","text":"10","correct":false},{"label":"D","text":"4","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_ADV', 2023, 'Maths', 'Calculus - Integration',
 '∫₀^π sin x dx equals:',
 '∫sin x dx = −cos x. Evaluated: [−cos x]₀^π = −cos π − (−cos 0) = −(−1) + 1 = 2.',
 '[{"label":"A","text":"0","correct":false},{"label":"B","text":"1","correct":false},{"label":"C","text":"2","correct":true},{"label":"D","text":"π","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_ADV', 2022, 'Maths', 'Probability',
 'Events A and B are independent. P(A) = 0.4, P(B) = 0.5. P(A∩B) is:',
 'For independent events: P(A∩B) = P(A)×P(B) = 0.4 × 0.5 = 0.2.',
 '[{"label":"A","text":"0.9","correct":false},{"label":"B","text":"0.7","correct":false},{"label":"C","text":"0.2","correct":true},{"label":"D","text":"0.45","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_ADV', 2021, 'Maths', '3D Geometry',
 'The equation of plane parallel to xy-plane passing through (1, 2, 5) is:',
 'Plane parallel to xy-plane has equation z = k. Passes through z = 5. Equation: z = 5.',
 '[{"label":"A","text":"x = 1","correct":false},{"label":"B","text":"y = 2","correct":false},{"label":"C","text":"z = 5","correct":true},{"label":"D","text":"x + y = 3","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_ADV', 2022, 'Maths', 'Calculus - Applications',
 'The function f(x) = x³ − 3x is decreasing on the interval:',
 'f''(x) = 3x² − 3 = 3(x²−1). f''(x) < 0 when x² < 1, i.e., −1 < x < 1.',
 '[{"label":"A","text":"(−∞, −1)","correct":false},{"label":"B","text":"(1, ∞)","correct":false},{"label":"C","text":"(−1, 1)","correct":true},{"label":"D","text":"(0, ∞)","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_ADV', 2023, 'Maths', 'Vectors',
 'The cross product of two parallel vectors is:',
 'If vectors are parallel, angle θ = 0°. |A×B| = |A||B|sin θ = 0. The cross product is the zero vector.',
 '[{"label":"A","text":"A unit vector","correct":false},{"label":"B","text":"The zero vector","correct":true},{"label":"C","text":"Maximum value","correct":false},{"label":"D","text":"Their dot product","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_ADV', 2021, 'Maths', 'Sequences and Series',
 'If three terms in GP are 2, x, 8, the value of x is:',
 'In GP: x² = 2 × 8 = 16. x = ±4. Since sequence is increasing positive, x = 4.',
 '[{"label":"A","text":"4 or −4","correct":false},{"label":"B","text":"5","correct":false},{"label":"C","text":"4","correct":true},{"label":"D","text":"10","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_ADV', 2022, 'Maths', 'Trigonometry',
 'The general solution of sin x = 1/2 is:',
 'sin x = 1/2 → x = π/6 or x = 5π/6 in [0, 2π]. General: x = nπ + (−1)ⁿ π/6.',
 '[{"label":"A","text":"x = nπ + π/6","correct":false},{"label":"B","text":"x = 2nπ ± π/6","correct":false},{"label":"C","text":"x = nπ + (−1)ⁿ π/6","correct":true},{"label":"D","text":"x = nπ/6","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_ADV', 2023, 'Maths', 'Calculus - Limits',
 'lim(x→∞) (1 + 1/x)ˣ equals:',
 'This is the definition of e (Euler''s number). lim(x→∞)(1 + 1/x)ˣ = e ≈ 2.718.',
 '[{"label":"A","text":"1","correct":false},{"label":"B","text":"∞","correct":false},{"label":"C","text":"e","correct":true},{"label":"D","text":"2","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_ADV', 2021, 'Maths', 'Permutations and Combinations',
 'How many 3-digit numbers can be formed using digits 1,2,3,4,5 without repetition?',
 'P(5,3) = 5!/(5−3)! = 5×4×3 = 60.',
 '[{"label":"A","text":"125","correct":false},{"label":"B","text":"60","correct":true},{"label":"C","text":"20","correct":false},{"label":"D","text":"10","correct":false}]',
 'B', 'mcq', 'easy', 4),

-- ── NEET · PHYSICS (47 questions) ───────────────────────────────────────────

('NEET', 2021, 'Physics', 'Kinematics',
 'A body starts from rest and moves with uniform acceleration a. The distance covered in the nth second is:',
 's_n = u + a(n − 1/2) = 0 + a(n − 1/2) = a(2n−1)/2.',
 '[{"label":"A","text":"an","correct":false},{"label":"B","text":"a(2n−1)/2","correct":true},{"label":"C","text":"an²/2","correct":false},{"label":"D","text":"a(n−1)","correct":false}]',
 'B', 'mcq', 'hard', 4),

('NEET', 2022, 'Physics', 'Kinematics',
 'The velocity of a particle is v = 3t² + 2t. The displacement from t = 0 to t = 2 s is:',
 'x = ∫₀² (3t²+2t) dt = [t³ + t²]₀² = 8 + 4 = 12 m.',
 '[{"label":"A","text":"8 m","correct":false},{"label":"B","text":"12 m","correct":true},{"label":"C","text":"16 m","correct":false},{"label":"D","text":"20 m","correct":false}]',
 'B', 'mcq', 'hard', 4),

('NEET', 2023, 'Physics', 'Laws of Motion',
 'The weight of a person in a lift accelerating upward at 2 m/s² is (mass = 60 kg, g = 10 m/s²):',
 'Apparent weight = m(g+a) = 60(10+2) = 60×12 = 720 N.',
 '[{"label":"A","text":"600 N","correct":false},{"label":"B","text":"480 N","correct":false},{"label":"C","text":"720 N","correct":true},{"label":"D","text":"660 N","correct":false}]',
 'C', 'mcq', 'medium', 4),

('NEET', 2021, 'Physics', 'Gravitation',
 'At what height above Earth''s surface is the gravitational acceleration g/4? (R = radius of Earth)',
 'g'' = g/(1+h/R)² = g/4 → (1+h/R)² = 4 → 1+h/R = 2 → h = R.',
 '[{"label":"A","text":"h = R/2","correct":false},{"label":"B","text":"h = R","correct":true},{"label":"C","text":"h = 2R","correct":false},{"label":"D","text":"h = 4R","correct":false}]',
 'B', 'mcq', 'hard', 4),

('NEET', 2022, 'Physics', 'Thermal Properties',
 'A metal rod of length 1 m expands by 1.2 mm when heated by 40°C. The coefficient of linear expansion is:',
 'α = ΔL/(L₀ × ΔT) = 0.0012/(1 × 40) = 3×10⁻⁵ /°C.',
 '[{"label":"A","text":"3×10⁻⁵ /°C","correct":true},{"label":"B","text":"3×10⁻⁴ /°C","correct":false},{"label":"C","text":"1.2×10⁻³ /°C","correct":false},{"label":"D","text":"4.8×10⁻⁵ /°C","correct":false}]',
 'A', 'mcq', 'medium', 4),

('NEET', 2023, 'Physics', 'Thermodynamics',
 'A Carnot engine operating between 600 K and 300 K has efficiency:',
 'η = 1 − T_cold/T_hot = 1 − 300/600 = 1 − 1/2 = 50%.',
 '[{"label":"A","text":"25%","correct":false},{"label":"B","text":"50%","correct":true},{"label":"C","text":"75%","correct":false},{"label":"D","text":"100%","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Physics', 'Oscillations',
 'The frequency of a vibrating string is doubled when:',
 'f = (1/2L)√(T/μ). f ∝ √T. To double f, T must be quadrupled (4T).',
 '[{"label":"A","text":"Length is doubled","correct":false},{"label":"B","text":"Tension is quadrupled","correct":true},{"label":"C","text":"Mass per unit length is doubled","correct":false},{"label":"D","text":"Tension is doubled","correct":false}]',
 'B', 'mcq', 'hard', 4),

('NEET', 2022, 'Physics', 'Waves',
 'The velocity of sound in air at 27°C is approximately (at 0°C it is 332 m/s):',
 'v ∝ √T. v₂ = 332 × √(300/273) = 332 × 1.048 ≈ 348 m/s.',
 '[{"label":"A","text":"320 m/s","correct":false},{"label":"B","text":"332 m/s","correct":false},{"label":"C","text":"348 m/s","correct":true},{"label":"D","text":"360 m/s","correct":false}]',
 'C', 'mcq', 'hard', 4),

('NEET', 2023, 'Physics', 'Electrostatics',
 'Gauss''s law states that the total electric flux through a closed surface is:',
 'Φ = Q_enclosed/ε₀. The flux depends only on charge enclosed, not the shape of surface.',
 '[{"label":"A","text":"Zero always","correct":false},{"label":"B","text":"Q_enclosed/ε₀","correct":true},{"label":"C","text":"ε₀/Q_enclosed","correct":false},{"label":"D","text":"Q_enclosed × ε₀","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Physics', 'Current Electricity',
 'Power dissipated in a resistor R carrying current I is:',
 'P = I²R = V²/R = VI. All three forms are equivalent.',
 '[{"label":"A","text":"IR","correct":false},{"label":"B","text":"I²R","correct":true},{"label":"C","text":"IR²","correct":false},{"label":"D","text":"I/R","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Physics', 'Magnetism',
 'The force on a charge q moving with velocity v in a magnetic field B is:',
 'Lorentz force: F = qv × B. Magnitude = qvB sin θ. Direction perpendicular to both v and B.',
 '[{"label":"A","text":"F = qvB","correct":false},{"label":"B","text":"F = qvB sin θ (where θ is angle between v and B)","correct":true},{"label":"C","text":"F = qB/v","correct":false},{"label":"D","text":"F = q/vB","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Physics', 'Optics',
 'A concave mirror has focal length 15 cm. An object at 45 cm gives image at:',
 '1/v + 1/u = 1/f. u=−45, f=−15. 1/v = 1/(−15) − 1/(−45) = −3/45 + 1/45 = −2/45. v = −22.5 cm.',
 '[{"label":"A","text":"−22.5 cm","correct":true},{"label":"B","text":"22.5 cm","correct":false},{"label":"C","text":"−45 cm","correct":false},{"label":"D","text":"30 cm","correct":false}]',
 'A', 'mcq', 'hard', 4),

('NEET', 2021, 'Physics', 'Dual Nature',
 'The stopping potential in photoelectric effect is independent of:',
 'Stopping potential depends on frequency (energy) of incident light, not intensity. Intensity affects photocurrent (number of electrons) not stopping potential.',
 '[{"label":"A","text":"Frequency of light","correct":false},{"label":"B","text":"Intensity of light","correct":true},{"label":"C","text":"Work function of metal","correct":false},{"label":"D","text":"Wavelength of light","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2022, 'Physics', 'Semiconductors',
 'The forbidden energy gap in silicon at room temperature is approximately:',
 'Si band gap ≈ 1.1 eV at room temperature. Ge ≈ 0.72 eV, GaAs ≈ 1.43 eV.',
 '[{"label":"A","text":"0.72 eV","correct":false},{"label":"B","text":"1.1 eV","correct":true},{"label":"C","text":"5.0 eV","correct":false},{"label":"D","text":"3.3 eV","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2023, 'Physics', 'Communication',
 'Which modulation technique is used in FM radio?',
 'FM = Frequency Modulation. The frequency of carrier wave varies with amplitude of message signal. Used in FM radio (88–108 MHz).',
 '[{"label":"A","text":"Amplitude modulation","correct":false},{"label":"B","text":"Pulse modulation","correct":false},{"label":"C","text":"Frequency modulation","correct":true},{"label":"D","text":"Phase modulation","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Physics', 'Nuclear Physics',
 'Mass number A and atomic number Z of a nucleus. After α-decay, the new nucleus has:',
 'α particle = ⁴He (mass 4, charge 2). After α-decay: A decreases by 4, Z decreases by 2.',
 '[{"label":"A","text":"A−2, Z−2","correct":false},{"label":"B","text":"A−4, Z−2","correct":true},{"label":"C","text":"A−4, Z−4","correct":false},{"label":"D","text":"A−2, Z−4","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Physics', 'Work Energy Power',
 'A body of mass 4 kg is raised through height 5 m. Work done against gravity is (g=10 m/s²):',
 'W = mgh = 4 × 10 × 5 = 200 J.',
 '[{"label":"A","text":"20 J","correct":false},{"label":"B","text":"200 J","correct":true},{"label":"C","text":"2000 J","correct":false},{"label":"D","text":"50 J","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Physics', 'Rotational Motion',
 'The angular momentum L is related to moment of inertia I and angular velocity ω as:',
 'L = Iω. This is rotational analogue of p = mv (linear momentum).',
 '[{"label":"A","text":"L = I/ω","correct":false},{"label":"B","text":"L = Iω","correct":true},{"label":"C","text":"L = ω/I","correct":false},{"label":"D","text":"L = I²ω","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Physics', 'Surface Tension',
 'The angle of contact for a liquid that does not wet a surface is:',
 'Angle of contact > 90° for non-wetting liquids (e.g., mercury on glass). < 90° for wetting liquids (e.g., water on glass).',
 '[{"label":"A","text":"0°","correct":false},{"label":"B","text":"Less than 90°","correct":false},{"label":"C","text":"Greater than 90°","correct":true},{"label":"D","text":"Exactly 90°","correct":false}]',
 'C', 'mcq', 'medium', 4),

('NEET', 2022, 'Physics', 'Electromagnetic Waves',
 'Infrared waves are used in:',
 'IR waves are used in remote controls, night vision, greenhouse heating, and physiotherapy (heat treatment). Wavelength 700 nm – 1 mm.',
 '[{"label":"A","text":"RADAR","correct":false},{"label":"B","text":"X-ray photography","correct":false},{"label":"C","text":"Remote controls and night vision","correct":true},{"label":"D","text":"UV sterilisation","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Physics', 'Fluid Mechanics',
 'The pressure at depth h in a liquid of density ρ is:',
 'P = P₀ + ρgh where P₀ is atmospheric pressure. Gauge pressure = ρgh.',
 '[{"label":"A","text":"ρg/h","correct":false},{"label":"B","text":"ρgh","correct":false},{"label":"C","text":"P₀ + ρgh","correct":true},{"label":"D","text":"P₀ − ρgh","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Physics', 'Capacitance',
 'The energy stored in a capacitor of capacitance C charged to voltage V is:',
 'E = ½CV². Can also be written as Q²/2C = QV/2.',
 '[{"label":"A","text":"CV","correct":false},{"label":"B","text":"CV²","correct":false},{"label":"C","text":"½CV²","correct":true},{"label":"D","text":"2CV²","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Physics', 'Alternating Current',
 'The impedance of a series RLC circuit at resonance equals:',
 'At resonance, X_L = X_C, so they cancel. Impedance Z = √(R² + (X_L − X_C)²) = R.',
 '[{"label":"A","text":"X_L","correct":false},{"label":"B","text":"X_C","correct":false},{"label":"C","text":"R","correct":true},{"label":"D","text":"√(R² + X_L²)","correct":false}]',
 'C', 'mcq', 'medium', 4),

('NEET', 2023, 'Physics', 'Atoms',
 'In Hydrogen spectrum, the Balmer series corresponds to transitions to:',
 'Balmer series: electrons fall to n = 2 level. Visible light range. Lyman series → n=1, Paschen → n=3.',
 '[{"label":"A","text":"n = 1","correct":false},{"label":"B","text":"n = 2","correct":true},{"label":"C","text":"n = 3","correct":false},{"label":"D","text":"n = 4","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Physics', 'Ray Optics',
 'A glass prism causes dispersion because:',
 'Different wavelengths (colours) travel at slightly different speeds in glass (refractive index varies with wavelength), causing them to refract by different angles.',
 '[{"label":"A","text":"Glass absorbs certain colours","correct":false},{"label":"B","text":"Refractive index of glass varies with wavelength","correct":true},{"label":"C","text":"Light undergoes total internal reflection","correct":false},{"label":"D","text":"Different colours have different intensities","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Physics', 'Laws of Motion',
 'If a body moves with uniform velocity, the net force on it is:',
 'Newton''s first law: uniform velocity → no acceleration → net force = 0.',
 '[{"label":"A","text":"Positive","correct":false},{"label":"B","text":"Negative","correct":false},{"label":"C","text":"Zero","correct":true},{"label":"D","text":"Constant but non-zero","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Physics', 'Gravitation',
 'The period of revolution of a satellite depends on:',
 'T = 2π√(r³/GM). Period depends on orbital radius r and mass of central body M, not on the satellite''s mass.',
 '[{"label":"A","text":"Mass of satellite","correct":false},{"label":"B","text":"Orbital radius and mass of planet","correct":true},{"label":"C","text":"Speed of satellite only","correct":false},{"label":"D","text":"Atmospheric density","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2021, 'Physics', 'Projectile Motion',
 'The horizontal range of a projectile is maximum when launched at angle:',
 'R = u²sin(2θ)/g. Maximum when sin(2θ) = 1 → 2θ = 90° → θ = 45°.',
 '[{"label":"A","text":"30°","correct":false},{"label":"B","text":"60°","correct":false},{"label":"C","text":"45°","correct":true},{"label":"D","text":"90°","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Physics', 'Electromagnetic Induction',
 'The unit of magnetic flux is:',
 'Magnetic flux Φ = B × A. SI unit: Tesla × m² = Weber (Wb).',
 '[{"label":"A","text":"Tesla","correct":false},{"label":"B","text":"Weber","correct":true},{"label":"C","text":"Henry","correct":false},{"label":"D","text":"Farad","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Physics', 'Waves',
 'In a transverse wave, the particles of the medium vibrate:',
 'In transverse waves: particle oscillation is perpendicular to the direction of wave propagation.',
 '[{"label":"A","text":"Parallel to wave propagation","correct":false},{"label":"B","text":"Perpendicular to wave propagation","correct":true},{"label":"C","text":"In circles","correct":false},{"label":"D","text":"Randomly","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Physics', 'Current Electricity',
 'Resistivity of a conductor depends on:',
 'Resistivity ρ is an intrinsic property of the material, depending on material type and temperature. NOT on dimensions.',
 '[{"label":"A","text":"Length of conductor","correct":false},{"label":"B","text":"Cross-sectional area","correct":false},{"label":"C","text":"Material and temperature","correct":true},{"label":"D","text":"Applied voltage","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Physics', 'Thermal Properties',
 'Heat transfer by radiation does not require a material medium. This is because radiation is:',
 'Radiation transfers heat via electromagnetic waves (IR), which can travel through vacuum. Conduction and convection require material medium.',
 '[{"label":"A","text":"A mechanical wave","correct":false},{"label":"B","text":"An electromagnetic wave","correct":true},{"label":"C","text":"A longitudinal wave","correct":false},{"label":"D","text":"A sound wave","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Physics', 'Oscillations',
 'In SHM, when the displacement equals half the amplitude, the ratio of kinetic to potential energy is:',
 'KE = ½k(A²−x²), PE = ½kx². At x = A/2: KE = ½k(3A²/4), PE = ½k(A²/4). KE/PE = 3.',
 '[{"label":"A","text":"1:1","correct":false},{"label":"B","text":"1:3","correct":false},{"label":"C","text":"3:1","correct":true},{"label":"D","text":"1:2","correct":false}]',
 'C', 'mcq', 'hard', 4),

('NEET', 2021, 'Physics', 'Magnetism',
 'The SI unit of magnetic field (B) is:',
 'SI unit of B is Tesla (T) = kg/(A·s²) = Wb/m². 1 T = 10⁴ Gauss.',
 '[{"label":"A","text":"Gauss","correct":false},{"label":"B","text":"Oersted","correct":false},{"label":"C","text":"Tesla","correct":true},{"label":"D","text":"Weber","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Physics', 'Optics',
 'A lens of focal length f produces a magnification m. The object distance is:',
 'Lens formula + m: m = v/u. From 1/v − 1/u = 1/f and m = v/u: u = f(1−m)/1 = f(1 − 1/m) → u = f(m−1)/m.',
 '[{"label":"A","text":"f(m+1)/m","correct":false},{"label":"B","text":"f(m−1)/m","correct":true},{"label":"C","text":"fm","correct":false},{"label":"D","text":"f/m","correct":false}]',
 'B', 'mcq', 'hard', 4),

('NEET', 2023, 'Physics', 'Electrostatics',
 'A capacitor is connected to a battery and then disconnected. If the plate separation is doubled, the energy stored:',
 'After disconnecting, charge Q is constant. E = Q²/2C. When d doubles, C halves (C=ε₀A/d). E = Q²/2(C/2) = 2×Q²/2C. Energy doubles.',
 '[{"label":"A","text":"Halves","correct":false},{"label":"B","text":"Stays same","correct":false},{"label":"C","text":"Doubles","correct":true},{"label":"D","text":"Quadruples","correct":false}]',
 'C', 'mcq', 'hard', 4)

ON CONFLICT DO NOTHING;
