-- Extended PYQ seed — Part 3: NEET Chemistry (46) + NEET Biology (92)

INSERT INTO public.pyq_content
  (exam, year, subject, chapter, question_text, solution_text, options, correct_option, question_type, difficulty, marks)
VALUES

-- ── NEET · CHEMISTRY (46 questions) ─────────────────────────────────────────

('NEET', 2021, 'Chemistry', 'Some Basic Concepts',
 'The molar mass of H₂SO₄ is:',
 'H₂SO₄: 2×1 + 32 + 4×16 = 2 + 32 + 64 = 98 g/mol.',
 '[{"label":"A","text":"96 g/mol","correct":false},{"label":"B","text":"98 g/mol","correct":true},{"label":"C","text":"100 g/mol","correct":false},{"label":"D","text":"80 g/mol","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Chemistry', 'Some Basic Concepts',
 'The number of molecules in 2 moles of water is (Nₐ = 6.022×10²³):',
 'Molecules = n × Nₐ = 2 × 6.022×10²³ = 12.044×10²³ ≈ 1.2×10²⁴.',
 '[{"label":"A","text":"6.022×10²³","correct":false},{"label":"B","text":"1.2×10²⁴","correct":true},{"label":"C","text":"3.01×10²³","correct":false},{"label":"D","text":"12×10²³","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Chemistry', 'Atomic Structure',
 'The electronic configuration of Fe (Z=26) is:',
 'Fe: [Ar] 3d⁶ 4s². Filling order follows Aufbau: 1s²2s²2p⁶3s²3p⁶3d⁶4s².',
 '[{"label":"A","text":"[Ar] 3d⁸","correct":false},{"label":"B","text":"[Ar] 3d⁶ 4s²","correct":true},{"label":"C","text":"[Ar] 4s² 4d⁶","correct":false},{"label":"D","text":"[Ar] 3d⁷ 4s¹","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2021, 'Chemistry', 'Periodic Properties',
 'Electronegativity increases as you go:',
 'Electronegativity increases: left to right across a period, and bottom to top in a group. F is most electronegative.',
 '[{"label":"A","text":"Down a group","correct":false},{"label":"B","text":"Right to left in a period","correct":false},{"label":"C","text":"Left to right across a period and up a group","correct":true},{"label":"D","text":"Left to right and down a group","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Chemistry', 'Chemical Bonding',
 'The number of sigma and pi bonds in CH₂=CH₂ (ethylene) is:',
 'C=C has 1σ + 1π. Each C−H bond is σ. Total: C−C (1σ) + C=C (1π) + 4 C−H (4σ) = 5σ + 1π.',
 '[{"label":"A","text":"4σ, 1π","correct":false},{"label":"B","text":"5σ, 1π","correct":true},{"label":"C","text":"5σ, 2π","correct":false},{"label":"D","text":"4σ, 2π","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2023, 'Chemistry', 'States of Matter',
 'At constant temperature, if the pressure of a gas is doubled, its volume:',
 'Boyle''s law: PV = constant. If P doubles, V halves.',
 '[{"label":"A","text":"Doubles","correct":false},{"label":"B","text":"Remains same","correct":false},{"label":"C","text":"Halves","correct":true},{"label":"D","text":"Quadruples","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Chemistry', 'Thermodynamics',
 'An endothermic reaction has:',
 'Endothermic: ΔH > 0. System absorbs heat from surroundings. Products have higher energy than reactants.',
 '[{"label":"A","text":"ΔH < 0","correct":false},{"label":"B","text":"ΔH = 0","correct":false},{"label":"C","text":"ΔH > 0","correct":true},{"label":"D","text":"ΔS < 0 always","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Chemistry', 'Equilibrium',
 'The Kw of water at 25°C is 10⁻¹⁴. The pH of pure water is:',
 'Kw = [H⁺][OH⁻] = 10⁻¹⁴. In pure water, [H⁺] = [OH⁻] = 10⁻⁷. pH = −log(10⁻⁷) = 7.',
 '[{"label":"A","text":"6","correct":false},{"label":"B","text":"7","correct":true},{"label":"C","text":"8","correct":false},{"label":"D","text":"14","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Chemistry', 'Redox Reactions',
 'In the reaction 2Mg + O₂ → 2MgO, magnesium is:',
 'Mg goes from 0 → +2 (loses electrons) = oxidised. O₂ goes from 0 → −2 (gains electrons) = reduced.',
 '[{"label":"A","text":"Reduced","correct":false},{"label":"B","text":"Oxidised","correct":true},{"label":"C","text":"Both oxidised and reduced","correct":false},{"label":"D","text":"Neither","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Chemistry', 'Hydrogen',
 'Hydrogen is placed in Group 1 of the periodic table because:',
 'H has 1 valence electron like alkali metals, forms H⁺ ions, and reacts with non-metals similarly. However, it also resembles halogens (forms H⁻, diatomic molecule).',
 '[{"label":"A","text":"It is a metal","correct":false},{"label":"B","text":"It has 1 valence electron like alkali metals","correct":true},{"label":"C","text":"It forms ionic bonds only","correct":false},{"label":"D","text":"It has the highest ionisation energy","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2022, 'Chemistry', 's-Block Elements',
 'Which of the following is the most abundant metal in the Earth''s crust?',
 'Aluminium (Al) is the most abundant metal in Earth''s crust (≈8%). It is a p-block element but this is a common factual question.',
 '[{"label":"A","text":"Iron","correct":false},{"label":"B","text":"Calcium","correct":false},{"label":"C","text":"Aluminium","correct":true},{"label":"D","text":"Sodium","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Chemistry', 'p-Block Elements',
 'The hybridisation of sulphur in SO₂ is:',
 'SO₂: S has 1 lone pair + 2 bonds to O = 3 electron domains → sp² hybridisation. Bent/V-shape geometry.',
 '[{"label":"A","text":"sp","correct":false},{"label":"B","text":"sp²","correct":true},{"label":"C","text":"sp³","correct":false},{"label":"D","text":"sp³d","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2021, 'Chemistry', 'd-Block Elements',
 'Which ion from the first row of transition metals is colourless?',
 'Zn²⁺ has d¹⁰ configuration — completely filled d-orbitals. No d-d transitions possible, so colourless. Sc³⁺ (d⁰) also colourless.',
 '[{"label":"A","text":"Cu²⁺","correct":false},{"label":"B","text":"Fe³⁺","correct":false},{"label":"C","text":"Zn²⁺","correct":true},{"label":"D","text":"Mn²⁺","correct":false}]',
 'C', 'mcq', 'medium', 4),

('NEET', 2022, 'Chemistry', 'Coordination Compounds',
 'In [Fe(CN)₆]⁴⁻, the oxidation state of Fe is:',
 'CN⁻ is −1 each. Let Fe = x. x + 6(−1) = −4. x = −4 + 6 = +2. Fe is +2.',
 '[{"label":"A","text":"+1","correct":false},{"label":"B","text":"+2","correct":true},{"label":"C","text":"+3","correct":false},{"label":"D","text":"+4","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2023, 'Chemistry', 'Organic Chemistry - Basics',
 'Which of the following is the correct IUPAC name of CH₃CH₂CH₂OH?',
 'Three carbon chain with −OH at C1: propan-1-ol.',
 '[{"label":"A","text":"Propan-2-ol","correct":false},{"label":"B","text":"Propan-1-ol","correct":true},{"label":"C","text":"1-hydroxypropane","correct":false},{"label":"D","text":"Propenol","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Chemistry', 'Hydrocarbons',
 'Which test is used to detect the presence of a carbon-carbon triple bond (alkyne)?',
 'Alkynes (terminal) react with ammoniacal silver nitrate to form a white precipitate (silver alkynide). Baeyer''s test (KMnO₄) also positive but not specific.',
 '[{"label":"A","text":"Tollens'' test","correct":false},{"label":"B","text":"Ammoniacal silver nitrate (forms white precipitate)","correct":true},{"label":"C","text":"2,4-DNP test","correct":false},{"label":"D","text":"Lucas test","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2022, 'Chemistry', 'Organic Halides',
 'Which compound undergoes SN1 reaction most readily?',
 'SN1 favoured by tertiary carbocation stability. (CH₃)₃CBr (tertiary) forms most stable 3° carbocation → fastest SN1.',
 '[{"label":"A","text":"CH₃Br","correct":false},{"label":"B","text":"CH₃CH₂Br","correct":false},{"label":"C","text":"(CH₃)₂CHBr","correct":false},{"label":"D","text":"(CH₃)₃CBr","correct":true}]',
 'D', 'mcq', 'medium', 4),

('NEET', 2023, 'Chemistry', 'Alcohols',
 'Ethanol reacts with sodium metal to produce:',
 'C₂H₅OH + Na → C₂H₅ONa (sodium ethoxide) + ½H₂. Active H on OH reacts with Na to release H₂ gas.',
 '[{"label":"A","text":"Ethylene and NaOH","correct":false},{"label":"B","text":"Sodium ethoxide and hydrogen gas","correct":true},{"label":"C","text":"Acetaldehyde and NaH","correct":false},{"label":"D","text":"Ether and NaCl","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Chemistry', 'Phenols',
 'Phenol is more acidic than ethanol because:',
 'Phenoxide ion is stabilised by resonance with benzene ring (charge delocalised over ring). Ethoxide has no resonance stabilisation. So phenol releases H⁺ more readily.',
 '[{"label":"A","text":"Phenol has higher molecular mass","correct":false},{"label":"B","text":"Phenoxide ion is stabilised by resonance","correct":true},{"label":"C","text":"Phenol is aromatic","correct":false},{"label":"D","text":"Ethanol is a gas at room temperature","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2022, 'Chemistry', 'Aldehydes Ketones',
 'Acetaldehyde on oxidation with acidic K₂Cr₂O₇ gives:',
 'CH₃CHO + [O] → CH₃COOH (acetic acid). Aldehyde oxidised to corresponding carboxylic acid.',
 '[{"label":"A","text":"Acetone","correct":false},{"label":"B","text":"Methanol","correct":false},{"label":"C","text":"Acetic acid","correct":true},{"label":"D","text":"Ethylene","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Chemistry', 'Carboxylic Acids',
 'The reaction of a carboxylic acid with an alcohol in presence of H₂SO₄ is called:',
 'Esterification: RCOOH + R''OH ⇌ RCOOR'' + H₂O. Produces ester + water. Catalysed by conc. H₂SO₄.',
 '[{"label":"A","text":"Saponification","correct":false},{"label":"B","text":"Esterification","correct":true},{"label":"C","text":"Hydrogenation","correct":false},{"label":"D","text":"Oxidation","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Chemistry', 'Amines',
 'Aniline (C₆H₅NH₂) is less basic than methylamine (CH₃NH₂) because:',
 'In aniline, lone pair on N is delocalised into benzene ring (resonance) → less available for donation. In methylamine, CH₃ donates electrons → lone pair more available.',
 '[{"label":"A","text":"Aniline has higher molecular mass","correct":false},{"label":"B","text":"Lone pair of N is delocalised into benzene ring in aniline","correct":true},{"label":"C","text":"Aniline does not form hydrogen bonds","correct":false},{"label":"D","text":"Methylamine is aromatic","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2022, 'Chemistry', 'Biomolecules',
 'Insulin is a:',
 'Insulin is a polypeptide hormone (protein) made of 51 amino acids in two chains, produced by beta cells of pancreas.',
 '[{"label":"A","text":"Lipid","correct":false},{"label":"B","text":"Polysaccharide","correct":false},{"label":"C","text":"Protein (polypeptide)","correct":true},{"label":"D","text":"Nucleic acid","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Chemistry', 'Polymers',
 'PVC (polyvinyl chloride) is made by polymerisation of:',
 'PVC = addition polymer of vinyl chloride (CH₂=CHCl). Each monomer is chloroethene.',
 '[{"label":"A","text":"Styrene","correct":false},{"label":"B","text":"Vinyl chloride (chloroethene)","correct":true},{"label":"C","text":"Acrylonitrile","correct":false},{"label":"D","text":"Ethylene","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Chemistry', 'Chemistry in Everyday Life',
 'Aspirin is chemically known as:',
 'Aspirin = acetylsalicylic acid (2-acetoxybenzoic acid). Used as analgesic, antipyretic, anti-inflammatory.',
 '[{"label":"A","text":"Acetaminophen","correct":false},{"label":"B","text":"Acetylsalicylic acid","correct":true},{"label":"C","text":"Salicylic acid","correct":false},{"label":"D","text":"Ibuprofen","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Chemistry', 'Solid State',
 'The coordination number of Na⁺ in NaCl crystal structure is:',
 'NaCl has rock salt structure: each Na⁺ is surrounded by 6 Cl⁻ ions (face-centred cubic), and vice versa. Coordination number = 6.',
 '[{"label":"A","text":"4","correct":false},{"label":"B","text":"8","correct":false},{"label":"C","text":"6","correct":true},{"label":"D","text":"12","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Chemistry', 'Solutions',
 'The colligative property that is used to determine molecular mass of a solute is:',
 'All colligative properties can determine molecular mass. Most commonly, osmotic pressure (π = iCRT) and elevation of boiling point or depression of freezing point are used. Depression of freezing point (ΔTf = iKfm) is common in practice.',
 '[{"label":"A","text":"Vapour pressure","correct":false},{"label":"B","text":"Depression of freezing point","correct":true},{"label":"C","text":"Surface tension","correct":false},{"label":"D","text":"Viscosity","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2021, 'Chemistry', 'Electrochemistry',
 'Rusting of iron is an example of:',
 'Rusting = electrochemical corrosion. Iron is oxidised (Fe → Fe²⁺) and oxygen is reduced. It is a galvanic cell process.',
 '[{"label":"A","text":"Physical change","correct":false},{"label":"B","text":"Electrochemical corrosion","correct":true},{"label":"C","text":"Reduction of iron","correct":false},{"label":"D","text":"Simple oxidation only","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Chemistry', 'Surface Chemistry',
 'Dialysis is used to purify:',
 'Dialysis removes small ions/molecules from colloids using a semipermeable membrane. Used to purify colloidal solutions (e.g., kidney dialysis).',
 '[{"label":"A","text":"True solutions","correct":false},{"label":"B","text":"Suspensions","correct":false},{"label":"C","text":"Colloidal solutions","correct":true},{"label":"D","text":"Emulsions only","correct":false}]',
 'C', 'mcq', 'medium', 4),

('NEET', 2023, 'Chemistry', 'General Principles of Metallurgy',
 'The process of heating an ore in the absence of air at a temperature below its melting point is called:',
 'Calcination: heating ore in absence of air. Used for carbonates and hydrated oxides. Roasting: heating in presence of air (for sulphides).',
 '[{"label":"A","text":"Roasting","correct":false},{"label":"B","text":"Smelting","correct":false},{"label":"C","text":"Calcination","correct":true},{"label":"D","text":"Leaching","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Chemistry', 'Organic Chemistry - GOC',
 'An electrophile is a species that:',
 'Electrophile (electron-lover) accepts an electron pair from a nucleophile. Examples: H⁺, Cl⁺, NO₂⁺, BF₃, AlCl₃.',
 '[{"label":"A","text":"Donates an electron pair","correct":false},{"label":"B","text":"Accepts an electron pair","correct":true},{"label":"C","text":"Has a negative charge always","correct":false},{"label":"D","text":"Contains only carbon","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Chemistry', 'Hydrocarbons',
 'The IUPAC name of CH₃-CH=CH-CH₃ is:',
 'Four carbon chain, double bond between C2 and C3: but-2-ene.',
 '[{"label":"A","text":"But-1-ene","correct":false},{"label":"B","text":"But-2-ene","correct":true},{"label":"C","text":"Butyne","correct":false},{"label":"D","text":"2-methylpropene","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Chemistry', 'Environmental Chemistry',
 'Which gas is primarily responsible for the greenhouse effect?',
 'CO₂ is the primary greenhouse gas responsible for global warming, though CH₄, N₂O, and H₂O vapour also contribute.',
 '[{"label":"A","text":"O₂","correct":false},{"label":"B","text":"N₂","correct":false},{"label":"C","text":"CO₂","correct":true},{"label":"D","text":"Ar","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Chemistry', 'Chemical Kinetics',
 'A zero-order reaction has rate = k. The unit of rate constant k is:',
 'Rate = k[A]⁰ = k. Units of rate = mol L⁻¹ s⁻¹. So k has units mol L⁻¹ s⁻¹.',
 '[{"label":"A","text":"s⁻¹","correct":false},{"label":"B","text":"L mol⁻¹ s⁻¹","correct":false},{"label":"C","text":"mol L⁻¹ s⁻¹","correct":true},{"label":"D","text":"mol⁻¹ L s⁻¹","correct":false}]',
 'C', 'mcq', 'medium', 4),

('NEET', 2022, 'Chemistry', 'Atomic Structure',
 'The energy of an electron in the nth orbit of hydrogen atom is:',
 'E_n = −13.6/n² eV. Negative sign = bound state. E₁ = −13.6 eV, E₂ = −3.4 eV.',
 '[{"label":"A","text":"E_n = 13.6 × n² eV","correct":false},{"label":"B","text":"E_n = −13.6/n² eV","correct":true},{"label":"C","text":"E_n = −13.6 × n eV","correct":false},{"label":"D","text":"E_n = 13.6/n eV","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Chemistry', 'Coordination Compounds',
 'Crystal field theory explains:',
 'Crystal Field Theory (CFT) explains the colour, magnetism, and stability of transition metal complexes by considering the effect of ligand electric field on d-orbital energy levels (d-orbital splitting).',
 '[{"label":"A","text":"Ionic bonding in salts","correct":false},{"label":"B","text":"Colour and magnetism of transition metal complexes","correct":true},{"label":"C","text":"Covalent bonding in organic compounds","correct":false},{"label":"D","text":"Shape of p-block hydrides","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2021, 'Chemistry', 'Thermodynamics',
 'Which process has ΔH = ΔU?',
 'ΔH = ΔU + ΔnRT. For Δn = 0 (equal moles of gas on both sides), ΔH = ΔU.',
 '[{"label":"A","text":"Any reaction at 25°C","correct":false},{"label":"B","text":"Reaction where Δn(gas) = 0","correct":true},{"label":"C","text":"Only isothermal reactions","correct":false},{"label":"D","text":"Only adiabatic reactions","correct":false}]',
 'B', 'mcq', 'hard', 4),

('NEET', 2022, 'Chemistry', 'Nuclear Chemistry',
 'Radiocarbon dating uses which isotope?',
 '¹⁴C (carbon-14) is a radioactive isotope with t₁/₂ ≈ 5730 years, used to date organic materials.',
 '[{"label":"A","text":"Carbon-12","correct":false},{"label":"B","text":"Carbon-14","correct":true},{"label":"C","text":"Uranium-235","correct":false},{"label":"D","text":"Tritium","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Chemistry', 'p-Block Elements',
 'Which of the following gases is used in making fertilisers?',
 'Ammonia (NH₃) is the primary feedstock for nitrogen fertilisers (urea, ammonium nitrate). Made by Haber process.',
 '[{"label":"A","text":"Chlorine","correct":false},{"label":"B","text":"Sulphur dioxide","correct":false},{"label":"C","text":"Ammonia","correct":true},{"label":"D","text":"Nitrous oxide","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Chemistry', 'Equilibrium',
 'Le Chatelier''s principle states that when a system at equilibrium is disturbed, it:',
 'Le Chatelier''s principle: The system shifts to counteract the disturbance and reach a new equilibrium.',
 '[{"label":"A","text":"Remains unaffected","correct":false},{"label":"B","text":"Shifts to counteract the disturbance","correct":true},{"label":"C","text":"Shifts in the direction of disturbance","correct":false},{"label":"D","text":"Decomposes completely","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Chemistry', 'Organic Chemistry - GOC',
 'The inductive effect in organic chemistry is:',
 'Inductive effect = electron displacement through sigma bonds due to electronegativity differences. Transmitted through bonds, decreasing with distance.',
 '[{"label":"A","text":"Displacement of electrons through pi bonds","correct":false},{"label":"B","text":"Displacement of electrons through sigma bonds due to electronegativity","correct":true},{"label":"C","text":"Effect of resonance on stability","correct":false},{"label":"D","text":"Hyperconjugation in alkenes","correct":false}]',
 'B', 'mcq', 'medium', 4),

-- ── NEET · BIOLOGY (92 questions) ───────────────────────────────────────────

('NEET', 2021, 'Biology', 'Diversity of Living Organisms',
 'The five-kingdom classification was proposed by:',
 'R.H. Whittaker (1969) proposed the five-kingdom classification: Monera, Protista, Fungi, Plantae, Animalia.',
 '[{"label":"A","text":"Carolus Linnaeus","correct":false},{"label":"B","text":"Ernst Haeckel","correct":false},{"label":"C","text":"R.H. Whittaker","correct":true},{"label":"D","text":"Carl Woese","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Diversity of Living Organisms',
 'Which of the following is NOT a characteristic of viruses?',
 'Viruses are not considered living cells. They lack cellular organisation, ribosomes, and cannot grow or metabolise independently — they are obligate intracellular parasites.',
 '[{"label":"A","text":"Contain nucleic acid","correct":false},{"label":"B","text":"Reproduce inside host cell","correct":false},{"label":"C","text":"Are cellular organisms","correct":true},{"label":"D","text":"Can be crystallised","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Diversity of Living Organisms',
 'Mycorrhiza is an association between:',
 'Mycorrhiza = mutualistic association between fungal hyphae and plant roots. Fungi help absorption of water/minerals; plant provides organic nutrients.',
 '[{"label":"A","text":"Algae and bacteria","correct":false},{"label":"B","text":"Fungus and plant roots","correct":true},{"label":"C","text":"Cyanobacteria and algae","correct":false},{"label":"D","text":"Virus and bacteria","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Structural Organisation',
 'The basic structural and functional unit of life is:',
 'The cell is the basic structural and functional unit of life. All living organisms are made of cells.',
 '[{"label":"A","text":"Tissue","correct":false},{"label":"B","text":"Organ","correct":false},{"label":"C","text":"Cell","correct":true},{"label":"D","text":"Molecule","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Cell Biology',
 'The fluid mosaic model of cell membrane was proposed by:',
 'Singer and Nicolson (1972) proposed the Fluid Mosaic Model: phospholipid bilayer with proteins embedded (integral) or attached (peripheral).',
 '[{"label":"A","text":"Watson and Crick","correct":false},{"label":"B","text":"Singer and Nicolson","correct":true},{"label":"C","text":"Robert Hooke","correct":false},{"label":"D","text":"Schleiden and Schwann","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Cell Biology',
 'Which organelle is responsible for sorting and packaging proteins for secretion?',
 'Golgi apparatus (Golgi complex) receives proteins from ER, modifies, sorts, and packages them into vesicles for secretion or delivery to other organelles.',
 '[{"label":"A","text":"Mitochondria","correct":false},{"label":"B","text":"Ribosome","correct":false},{"label":"C","text":"Golgi apparatus","correct":true},{"label":"D","text":"Lysosome","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Cell Biology',
 'Lysosomes are known as "suicide bags" because they:',
 'Lysosomes contain hydrolytic enzymes. In autolysis, they digest their own cell contents (cellular self-destruction), hence "suicide bags".',
 '[{"label":"A","text":"Kill bacteria","correct":false},{"label":"B","text":"Contain enzymes that can digest the cell itself","correct":true},{"label":"C","text":"Produce ATP","correct":false},{"label":"D","text":"Synthesise proteins","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Cell Biology',
 'The site of ribosome synthesis in eukaryotic cells is:',
 'Ribosomes are assembled in the nucleolus, which is inside the nucleus. rRNA is transcribed in nucleolus and combined with proteins.',
 '[{"label":"A","text":"Mitochondria","correct":false},{"label":"B","text":"Rough ER","correct":false},{"label":"C","text":"Nucleolus","correct":true},{"label":"D","text":"Cytoplasm","correct":false}]',
 'C', 'mcq', 'medium', 4),

('NEET', 2023, 'Biology', 'Biomolecules',
 'The most abundant organic compound in the biosphere is:',
 'Cellulose is the most abundant organic compound on Earth — it is the structural component of plant cell walls.',
 '[{"label":"A","text":"Protein","correct":false},{"label":"B","text":"DNA","correct":false},{"label":"C","text":"Cellulose","correct":true},{"label":"D","text":"Starch","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Biomolecules',
 'Enzymes are biological catalysts made of:',
 'Enzymes are mostly proteins (polypeptides). Some are RNA molecules (ribozymes). They lower activation energy without being consumed.',
 '[{"label":"A","text":"Lipids","correct":false},{"label":"B","text":"Proteins (polypeptides)","correct":true},{"label":"C","text":"Carbohydrates","correct":false},{"label":"D","text":"Nucleic acids only","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Cell Division',
 'Which phase of mitosis involves alignment of chromosomes at the cell equator?',
 'Metaphase: chromosomes align at the metaphase plate (equatorial plane). Spindle fibres attach to centromeres.',
 '[{"label":"A","text":"Prophase","correct":false},{"label":"B","text":"Metaphase","correct":true},{"label":"C","text":"Anaphase","correct":false},{"label":"D","text":"Telophase","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Cell Division',
 'Meiosis results in:',
 'Meiosis: reduction division. One diploid (2n) cell → four haploid (n) cells. Occurs in gonads for gamete formation. Genetic variation via crossing over.',
 '[{"label":"A","text":"Two diploid cells","correct":false},{"label":"B","text":"Four haploid cells","correct":true},{"label":"C","text":"Two haploid cells","correct":false},{"label":"D","text":"Four diploid cells","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Plant Physiology - Transport',
 'The movement of water from soil to root cells occurs by:',
 'Osmosis: water moves from high water potential (soil) to low water potential (root cells) through semipermeable membrane.',
 '[{"label":"A","text":"Active transport","correct":false},{"label":"B","text":"Osmosis","correct":true},{"label":"C","text":"Diffusion of sugars","correct":false},{"label":"D","text":"Cytoplasmic streaming","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Plant Physiology - Mineral Nutrition',
 'Which element is essential for nitrogen fixation by Rhizobium?',
 'Molybdenum (Mo) is essential component of nitrogenase enzyme complex used by Rhizobium for biological N₂ fixation.',
 '[{"label":"A","text":"Iron","correct":false},{"label":"B","text":"Copper","correct":false},{"label":"C","text":"Molybdenum","correct":true},{"label":"D","text":"Zinc","correct":false}]',
 'C', 'mcq', 'hard', 4),

('NEET', 2023, 'Biology', 'Plant Physiology - Photosynthesis',
 'The light reactions of photosynthesis occur in the:',
 'Light reactions (photosystems I and II, electron transport, photophosphorylation) occur in thylakoid membranes (grana) of chloroplast.',
 '[{"label":"A","text":"Stroma","correct":false},{"label":"B","text":"Thylakoid membrane","correct":true},{"label":"C","text":"Cytoplasm","correct":false},{"label":"D","text":"Mitochondria","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Plant Physiology - Photosynthesis',
 'The first stable product of the Calvin cycle is:',
 '3-Phosphoglycerate (3-PGA) is the first stable 3-carbon compound formed when CO₂ is fixed by RuBisCO to RuBP.',
 '[{"label":"A","text":"Glucose","correct":false},{"label":"B","text":"Pyruvate","correct":false},{"label":"C","text":"3-Phosphoglycerate (3-PGA)","correct":true},{"label":"D","text":"Oxaloacetate","correct":false}]',
 'C', 'mcq', 'medium', 4),

('NEET', 2022, 'Biology', 'Plant Physiology - Respiration',
 'In which stage of cellular respiration is the maximum ATP produced?',
 'Oxidative phosphorylation (electron transport chain) in mitochondria produces 32–34 ATP. Glycolysis: 2 ATP; Krebs cycle: 2 ATP (direct).',
 '[{"label":"A","text":"Glycolysis","correct":false},{"label":"B","text":"Krebs cycle","correct":false},{"label":"C","text":"Oxidative phosphorylation (ETC)","correct":true},{"label":"D","text":"Fermentation","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Plant Physiology - Growth Hormones',
 'Which plant hormone promotes cell elongation and is responsible for phototropism?',
 'Auxin (IAA - indole-3-acetic acid) promotes cell elongation. In phototropism, auxin accumulates on the shaded side → more elongation → bending toward light.',
 '[{"label":"A","text":"Cytokinin","correct":false},{"label":"B","text":"Gibberellin","correct":false},{"label":"C","text":"Auxin","correct":true},{"label":"D","text":"Abscisic acid","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Human Physiology - Digestion',
 'The enzyme that converts starch to maltose in the mouth is:',
 'Salivary amylase (ptyalin) in saliva breaks down starch to maltose in the mouth (oral cavity).',
 '[{"label":"A","text":"Pepsin","correct":false},{"label":"B","text":"Trypsin","correct":false},{"label":"C","text":"Salivary amylase","correct":true},{"label":"D","text":"Lipase","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Human Physiology - Digestion',
 'Bile is produced by the liver and stored in:',
 'Bile is produced in the liver, stored in the gall bladder, and released into the duodenum during fat digestion.',
 '[{"label":"A","text":"Pancreas","correct":false},{"label":"B","text":"Small intestine","correct":false},{"label":"C","text":"Gall bladder","correct":true},{"label":"D","text":"Stomach","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Human Physiology - Breathing',
 'The respiratory centre that controls the rhythm of breathing is located in:',
 'The medulla oblongata (brainstem) contains the respiratory control centre (dorsal and ventral respiratory groups) that sets the breathing rhythm.',
 '[{"label":"A","text":"Cerebellum","correct":false},{"label":"B","text":"Medulla oblongata","correct":true},{"label":"C","text":"Cerebral cortex","correct":false},{"label":"D","text":"Hypothalamus","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Human Physiology - Breathing',
 'The functional unit of the lung is:',
 'The alveolus (plural: alveoli) is the tiny air sac where gas exchange occurs between air and blood.',
 '[{"label":"A","text":"Bronchiole","correct":false},{"label":"B","text":"Bronchus","correct":false},{"label":"C","text":"Alveolus","correct":true},{"label":"D","text":"Trachea","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Human Physiology - Circulation',
 'The SA node is called the "pacemaker of the heart" because it:',
 'The sinoatrial (SA) node, located in the right atrium, generates spontaneous electrical impulses that initiate each heartbeat and sets the heart rate.',
 '[{"label":"A","text":"Is the largest node","correct":false},{"label":"B","text":"Initiates the electrical impulse for each heartbeat","correct":true},{"label":"C","text":"Regulates blood pressure","correct":false},{"label":"D","text":"Connects atria and ventricles","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Human Physiology - Excretion',
 'The functional unit of the kidney is:',
 'The nephron is the functional unit of the kidney. About 1 million nephrons per kidney filter blood and form urine.',
 '[{"label":"A","text":"Glomerulus","correct":false},{"label":"B","text":"Nephron","correct":true},{"label":"C","text":"Loop of Henle","correct":false},{"label":"D","text":"Bowman''s capsule","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Human Physiology - Excretion',
 'Urea is formed in the:',
 'Urea is formed in the liver by the ornithine cycle (urea cycle) from ammonia and CO₂. It is then transported to kidneys for excretion.',
 '[{"label":"A","text":"Kidney","correct":false},{"label":"B","text":"Blood","correct":false},{"label":"C","text":"Liver","correct":true},{"label":"D","text":"Intestine","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Human Physiology - Locomotion',
 'Which protein is responsible for muscle contraction?',
 'Muscle contraction involves sliding of actin (thin filaments) over myosin (thick filaments). Both actin and myosin are contractile proteins. Cross-bridge formation between them causes contraction.',
 '[{"label":"A","text":"Collagen and elastin","correct":false},{"label":"B","text":"Actin and myosin","correct":true},{"label":"C","text":"Keratin and fibrin","correct":false},{"label":"D","text":"Haemoglobin and myoglobin","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Human Physiology - Neural Control',
 'The myelin sheath around nerve fibres is formed by:',
 'In PNS: Schwann cells form myelin. In CNS: oligodendrocytes form myelin. Myelin increases conduction speed (saltatory conduction).',
 '[{"label":"A","text":"Astrocytes","correct":false},{"label":"B","text":"Schwann cells (PNS) and oligodendrocytes (CNS)","correct":true},{"label":"C","text":"Microglia","correct":false},{"label":"D","text":"Neurons","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2021, 'Biology', 'Human Physiology - Endocrine',
 'The master gland of the endocrine system is:',
 'Pituitary gland (hypophysis) is called the master gland because it controls many other endocrine glands through trophic hormones. It is controlled by hypothalamus.',
 '[{"label":"A","text":"Thyroid gland","correct":false},{"label":"B","text":"Adrenal gland","correct":false},{"label":"C","text":"Pituitary gland","correct":true},{"label":"D","text":"Pancreas","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Human Physiology - Endocrine',
 'Insulin deficiency causes:',
 'Insulin (from beta cells of islets of Langerhans, pancreas) promotes glucose uptake. Deficiency → hyperglycaemia (high blood sugar) → diabetes mellitus.',
 '[{"label":"A","text":"Gigantism","correct":false},{"label":"B","text":"Diabetes mellitus","correct":true},{"label":"C","text":"Cretinism","correct":false},{"label":"D","text":"Cushing''s syndrome","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Reproduction - Plants',
 'Double fertilisation is unique to:',
 'Double fertilisation: one sperm fertilises egg (→ zygote/2n), another fertilises polar nuclei (→ endosperm/3n). Unique to angiosperms (flowering plants).',
 '[{"label":"A","text":"Gymnosperms","correct":false},{"label":"B","text":"Bryophytes","correct":false},{"label":"C","text":"Angiosperms","correct":true},{"label":"D","text":"Pteridophytes","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Reproduction - Humans',
 'The site of fertilisation in females is:',
 'Fertilisation normally occurs in the fallopian tube (uterine tube), specifically in the ampullary-isthmic junction.',
 '[{"label":"A","text":"Uterus","correct":false},{"label":"B","text":"Ovary","correct":false},{"label":"C","text":"Fallopian tube","correct":true},{"label":"D","text":"Vagina","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Genetics - Mendelism',
 'A dihybrid cross produces offspring in the ratio:',
 'Dihybrid cross (AaBb × AaBb): phenotypic ratio = 9:3:3:1. Genotypic ratio has 9 classes.',
 '[{"label":"A","text":"3:1","correct":false},{"label":"B","text":"1:2:1","correct":false},{"label":"C","text":"9:3:3:1","correct":true},{"label":"D","text":"1:1:1:1","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Genetics - Chromosomal Basis',
 'Turner syndrome (45, X) occurs due to:',
 'Turner syndrome: female with 45 chromosomes (45,X), missing one X chromosome due to non-disjunction. Features: short stature, gonadal dysgenesis.',
 '[{"label":"A","text":"Trisomy of chromosome 21","correct":false},{"label":"B","text":"Monosomy of X chromosome (45,X)","correct":true},{"label":"C","text":"Extra X chromosome (47,XXX)","correct":false},{"label":"D","text":"Y-linked gene mutation","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2021, 'Biology', 'Genetics - Molecular',
 'The process of copying DNA into mRNA is called:',
 'Transcription: DNA → mRNA (in nucleus). mRNA then moves to ribosome for translation (mRNA → protein).',
 '[{"label":"A","text":"Translation","correct":false},{"label":"B","text":"Replication","correct":false},{"label":"C","text":"Transcription","correct":true},{"label":"D","text":"Transduction","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Genetics - Molecular',
 'The anticodon is found on:',
 'Anticodon is a three-nucleotide sequence on tRNA that is complementary to the codon on mRNA, ensuring correct amino acid is added.',
 '[{"label":"A","text":"mRNA","correct":false},{"label":"B","text":"rRNA","correct":false},{"label":"C","text":"tRNA","correct":true},{"label":"D","text":"DNA","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Genetics - Molecular',
 'The enzyme that unwinds the DNA double helix during replication is:',
 'Helicase unwinds and separates the two DNA strands by breaking hydrogen bonds between base pairs at the replication fork.',
 '[{"label":"A","text":"DNA polymerase","correct":false},{"label":"B","text":"Ligase","correct":false},{"label":"C","text":"Helicase","correct":true},{"label":"D","text":"Primase","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Evolution',
 'The theory of natural selection was proposed by:',
 'Charles Darwin proposed the theory of natural selection in "On the Origin of Species" (1859). Survival of the fittest.',
 '[{"label":"A","text":"Lamarck","correct":false},{"label":"B","text":"Charles Darwin","correct":true},{"label":"C","text":"Mendel","correct":false},{"label":"D","text":"Hugo de Vries","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Evolution',
 'Hardy-Weinberg equilibrium requires which condition?',
 'Hardy-Weinberg equilibrium: no evolution occurring. Conditions: large population, random mating, no mutation, no selection, no gene flow.',
 '[{"label":"A","text":"Natural selection","correct":false},{"label":"B","text":"Large population with random mating and no mutations","correct":true},{"label":"C","text":"Small isolated population","correct":false},{"label":"D","text":"High mutation rate","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2023, 'Biology', 'Ecology',
 'The pyramid of energy is always:',
 'Energy pyramid is always upright — energy decreases at each trophic level (only ~10% transferred). Never inverted.',
 '[{"label":"A","text":"Inverted","correct":false},{"label":"B","text":"Spindle-shaped","correct":false},{"label":"C","text":"Upright","correct":true},{"label":"D","text":"Can be inverted or upright","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Ecology',
 'The term "ecosystem" was coined by:',
 'A.G. Tansley (1935) coined the term "ecosystem" to describe the biotic community and its abiotic environment as a functional unit.',
 '[{"label":"A","text":"Ernst Haeckel","correct":false},{"label":"B","text":"Charles Elton","correct":false},{"label":"C","text":"A.G. Tansley","correct":true},{"label":"D","text":"Eugene Odum","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Ecology',
 'Which of the following is a biotic component of an ecosystem?',
 'Biotic = living components. Microorganisms, plants, animals = biotic. Temperature, water, light, soil = abiotic.',
 '[{"label":"A","text":"Temperature","correct":false},{"label":"B","text":"Sunlight","correct":false},{"label":"C","text":"Microorganisms","correct":true},{"label":"D","text":"Mineral nutrients","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Ecology - Biodiversity',
 'The region with maximum biodiversity on Earth is:',
 'Tropical rainforests (especially Amazon basin) have maximum biodiversity due to warm climate, high rainfall, and stable environment over millions of years.',
 '[{"label":"A","text":"Polar regions","correct":false},{"label":"B","text":"Deserts","correct":false},{"label":"C","text":"Tropical rainforests","correct":true},{"label":"D","text":"Temperate grasslands","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Biotechnology',
 'Restriction enzymes are used in genetic engineering to:',
 'Restriction endonucleases (restriction enzymes) cut DNA at specific recognition sequences (palindromes), producing fragments for cloning.',
 '[{"label":"A","text":"Join DNA fragments","correct":false},{"label":"B","text":"Cut DNA at specific sequences","correct":true},{"label":"C","text":"Copy DNA","correct":false},{"label":"D","text":"Translate mRNA","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Biotechnology',
 'The enzyme used to join DNA fragments in recombinant DNA technology is:',
 'DNA ligase joins the cut ends of DNA fragments by forming phosphodiester bonds. It seals the "sticky ends" or "blunt ends".',
 '[{"label":"A","text":"DNA polymerase","correct":false},{"label":"B","text":"Helicase","correct":false},{"label":"C","text":"DNA ligase","correct":true},{"label":"D","text":"Restriction enzyme","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Biotechnology',
 'The first genetically engineered hormone produced using recombinant DNA technology was:',
 'Human insulin (Humulin) was the first recombinant protein approved for medical use (1982). Made by inserting human insulin gene into E. coli.',
 '[{"label":"A","text":"Growth hormone","correct":false},{"label":"B","text":"Cortisol","correct":false},{"label":"C","text":"Insulin","correct":true},{"label":"D","text":"Thyroxine","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Plant Kingdom',
 'Which of the following is a bryophyte?',
 'Bryophytes = non-vascular land plants (amphibians of plant kingdom). Moss (Funaria), Liverworts (Marchantia), Hornworts. Ferns are pteridophytes.',
 '[{"label":"A","text":"Fern","correct":false},{"label":"B","text":"Moss","correct":true},{"label":"C","text":"Pine","correct":false},{"label":"D","text":"Rose","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Plant Kingdom',
 'In the life cycle of a moss, the dominant generation is:',
 'Bryophytes (mosses) have dominant gametophyte generation (n). The sporophyte (2n) is dependent on gametophyte. Opposite in vascular plants.',
 '[{"label":"A","text":"Sporophyte","correct":false},{"label":"B","text":"Gametophyte","correct":true},{"label":"C","text":"Both equally dominant","correct":false},{"label":"D","text":"Endosperm","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2023, 'Biology', 'Animal Kingdom',
 'The defining characteristic of phylum Chordata is the presence of:',
 'Chordates have: notochord, dorsal hollow nerve cord, pharyngeal slits (gill slits), and post-anal tail — at some stage of life cycle.',
 '[{"label":"A","text":"Backbone","correct":false},{"label":"B","text":"Notochord, dorsal nerve cord, pharyngeal slits","correct":true},{"label":"C","text":"Four-chambered heart","correct":false},{"label":"D","text":"Warm blood","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2021, 'Biology', 'Animal Kingdom',
 'The excretory organ of earthworm is:',
 'Earthworm excretes via nephridia (segmentally arranged tubular organs). Not kidneys (vertebrates) or malpighian tubules (insects).',
 '[{"label":"A","text":"Kidney","correct":false},{"label":"B","text":"Nephridia","correct":true},{"label":"C","text":"Malpighian tubules","correct":false},{"label":"D","text":"Green glands","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Genetics',
 'A person with blood group AB has:',
 'Blood group AB: genotype IᵃIᵇ. Both A and B antigens on RBC surface. No antibodies in plasma (universal recipient). Both alleles are codominant.',
 '[{"label":"A","text":"Only A antigen","correct":false},{"label":"B","text":"Only B antigen","correct":false},{"label":"C","text":"Both A and B antigens","correct":true},{"label":"D","text":"No antigens","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Human Physiology - Circulation',
 'The QRS complex in an ECG represents:',
 'QRS complex = ventricular depolarisation (contraction of ventricles). P wave = atrial depolarisation, T wave = ventricular repolarisation.',
 '[{"label":"A","text":"Atrial depolarisation","correct":false},{"label":"B","text":"Ventricular depolarisation","correct":true},{"label":"C","text":"Atrial repolarisation","correct":false},{"label":"D","text":"Ventricular repolarisation","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2021, 'Biology', 'Human Physiology - Breathing',
 'Tidal volume is the volume of air:',
 'Tidal volume ≈ 500 mL = volume inhaled or exhaled in one normal breath. ERV and IRV are additional reserve volumes.',
 '[{"label":"A","text":"Inhaled by maximum effort","correct":false},{"label":"B","text":"Inhaled or exhaled in one normal breath","correct":true},{"label":"C","text":"Remaining after forced exhalation","correct":false},{"label":"D","text":"Total lung capacity","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Reproduction',
 'Parthenogenesis is the development of:',
 'Parthenogenesis: development of an egg into a new organism without fertilisation. Example: drones (males) in honeybees develop from unfertilised eggs.',
 '[{"label":"A","text":"Organism from fertilised egg","correct":false},{"label":"B","text":"Organism from unfertilised egg","correct":true},{"label":"C","text":"Sperm without egg","correct":false},{"label":"D","text":"Clone by binary fission","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Ecology',
 'Which type of interaction benefits both species?',
 'Mutualism: both species benefit (+/+). Examples: Rhizobium and legumes, mycorrhiza, cleaner fish and sharks, bees and flowers.',
 '[{"label":"A","text":"Commensalism","correct":false},{"label":"B","text":"Predation","correct":false},{"label":"C","text":"Mutualism","correct":true},{"label":"D","text":"Parasitism","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Ecology',
 'The number of individuals per unit area at a given time is called:',
 'Population density = number of individuals per unit area (or volume). It can be measured by absolute or relative methods.',
 '[{"label":"A","text":"Population growth","correct":false},{"label":"B","text":"Population density","correct":true},{"label":"C","text":"Biotic potential","correct":false},{"label":"D","text":"Carrying capacity","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Human Health and Disease',
 'AIDS is caused by:',
 'AIDS (Acquired Immunodeficiency Syndrome) is caused by HIV (Human Immunodeficiency Virus), a retrovirus that attacks CD4+ T-lymphocytes.',
 '[{"label":"A","text":"HIV","correct":true},{"label":"B","text":"Plasmodium","correct":false},{"label":"C","text":"Mycobacterium","correct":false},{"label":"D","text":"Candida","correct":false}]',
 'A', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Human Health and Disease',
 'Which disease is caused by Plasmodium falciparum?',
 'Malignant malaria (most dangerous form) is caused by Plasmodium falciparum. P. vivax causes benign tertian malaria. Transmitted by female Anopheles mosquito.',
 '[{"label":"A","text":"Dengue","correct":false},{"label":"B","text":"Malaria (malignant form)","correct":true},{"label":"C","text":"Filariasis","correct":false},{"label":"D","text":"Chikungunya","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Ecology - Environmental Issues',
 'The Montreal Protocol (1987) aimed to protect the:',
 'Montreal Protocol: international agreement to phase out ozone-depleting substances (CFCs, halons). Aimed at protecting the ozone layer.',
 '[{"label":"A","text":"Tropical forests","correct":false},{"label":"B","text":"Ozone layer","correct":true},{"label":"C","text":"Arctic ice caps","correct":false},{"label":"D","text":"Ocean biodiversity","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Plant Physiology - Seeds',
 'The hormone that breaks seed dormancy and promotes germination is:',
 'Gibberellins promote seed germination by stimulating the synthesis of α-amylase which mobilises starch in endosperm.',
 '[{"label":"A","text":"Abscisic acid","correct":false},{"label":"B","text":"Ethylene","correct":false},{"label":"C","text":"Gibberellin","correct":true},{"label":"D","text":"Cytokinin","correct":false}]',
 'C', 'mcq', 'medium', 4),

('NEET', 2023, 'Biology', 'Genetics - Sex Determination',
 'In humans, sex is determined by the:',
 'Human sex determined by sex chromosomes: XX = female, XY = male. Male determines the sex of offspring (Y from father).',
 '[{"label":"A","text":"Mother (XX chromosomes)","correct":false},{"label":"B","text":"Father (X or Y chromosome contributed)","correct":true},{"label":"C","text":"Environmental temperature","correct":false},{"label":"D","text":"Autosomal genes","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Plant Physiology - Photoperiodism',
 'Short-day plants flower when:',
 'Short-day plants (SDPs) require a dark period LONGER than a critical duration. They flower in short days/long nights (autumn/winter). Actually it is the length of dark period that matters.',
 '[{"label":"A","text":"Day length is longer than critical length","correct":false},{"label":"B","text":"Night length exceeds the critical dark period","correct":true},{"label":"C","text":"Temperature is low","correct":false},{"label":"D","text":"Light intensity is high","correct":false}]',
 'B', 'mcq', 'hard', 4),

('NEET', 2022, 'Biology', 'Ecology',
 'Eutrophication refers to:',
 'Eutrophication: excessive growth of algae in water bodies due to nutrient enrichment (nitrogen, phosphorus). Leads to algal blooms, decreased O₂, fish death.',
 '[{"label":"A","text":"Pollution by heavy metals","correct":false},{"label":"B","text":"Excessive algal growth due to nutrient enrichment of water","correct":true},{"label":"C","text":"Deforestation of tropical forests","correct":false},{"label":"D","text":"Soil degradation","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Human Health',
 'Colostrum is rich in:',
 'Colostrum (first milk after birth) is rich in immunoglobulins (especially IgA), providing passive immunity to the newborn.',
 '[{"label":"A","text":"Fats","correct":false},{"label":"B","text":"Carbohydrates","correct":false},{"label":"C","text":"Immunoglobulins (antibodies)","correct":true},{"label":"D","text":"Vitamins only","correct":false}]',
 'C', 'mcq', 'medium', 4),

('NEET', 2021, 'Biology', 'Cell Biology',
 'Which is the longest phase of the cell cycle?',
 'Interphase (G1 + S + G2) is the longest phase. G1 (growth) is typically the longest sub-phase. Mitosis (M phase) is the shortest.',
 '[{"label":"A","text":"Prophase","correct":false},{"label":"B","text":"S phase","correct":false},{"label":"C","text":"G1 phase (interphase)","correct":true},{"label":"D","text":"M phase","correct":false}]',
 'C', 'mcq', 'medium', 4),

('NEET', 2022, 'Biology', 'Genetics',
 'Phenylketonuria (PKU) is an example of:',
 'PKU is an autosomal recessive metabolic disorder — deficiency of phenylalanine hydroxylase. If untreated, causes intellectual disability.',
 '[{"label":"A","text":"X-linked dominant disorder","correct":false},{"label":"B","text":"Autosomal recessive disorder","correct":true},{"label":"C","text":"Chromosomal abnormality","correct":false},{"label":"D","text":"Autosomal dominant disorder","correct":false}]',
 'B', 'mcq', 'medium', 4),

('NEET', 2023, 'Biology', 'Biotechnology',
 'PCR (Polymerase Chain Reaction) is used to:',
 'PCR amplifies specific DNA sequences in vitro using thermostable Taq DNA polymerase, through cycles of denaturation, annealing, and extension.',
 '[{"label":"A","text":"Separate DNA fragments by size","correct":false},{"label":"B","text":"Amplify specific DNA sequences","correct":true},{"label":"C","text":"Cut DNA at restriction sites","correct":false},{"label":"D","text":"Sequence DNA","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Ecology',
 'Which of the following is an example of ex-situ conservation?',
 'Ex-situ = conservation outside natural habitat. Zoological parks, botanical gardens, seed banks, gene banks = ex-situ. Biosphere reserves = in-situ.',
 '[{"label":"A","text":"National parks","correct":false},{"label":"B","text":"Biosphere reserves","correct":false},{"label":"C","text":"Zoological parks and seed banks","correct":true},{"label":"D","text":"Wildlife sanctuaries","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2022, 'Biology', 'Human Physiology',
 'Which blood cells are responsible for the immune response?',
 'Leucocytes (white blood cells) — especially lymphocytes (T cells, B cells) — are responsible for specific immune responses.',
 '[{"label":"A","text":"Erythrocytes","correct":false},{"label":"B","text":"Platelets","correct":false},{"label":"C","text":"Leucocytes (WBCs)","correct":true},{"label":"D","text":"Thrombocytes","correct":false}]',
 'C', 'mcq', 'easy', 4),

('NEET', 2023, 'Biology', 'Cell Biology',
 'Active transport differs from passive transport in that it:',
 'Active transport requires energy (ATP) and moves substances against their concentration gradient (low → high). Passive transport is down the gradient, no energy needed.',
 '[{"label":"A","text":"Occurs only in plant cells","correct":false},{"label":"B","text":"Requires energy and moves against concentration gradient","correct":true},{"label":"C","text":"Uses a concentration gradient","correct":false},{"label":"D","text":"Is faster than passive transport","correct":false}]',
 'B', 'mcq', 'easy', 4),

('NEET', 2021, 'Biology', 'Animal Kingdom',
 'Which of the following is a cold-blooded (ectothermic) animal?',
 'Cold-blooded = ectotherms: body temperature varies with environment. Reptiles, amphibians, fish, invertebrates. Birds and mammals are endotherms (warm-blooded).',
 '[{"label":"A","text":"Bat","correct":false},{"label":"B","text":"Whale","correct":false},{"label":"C","text":"Lizard","correct":true},{"label":"D","text":"Eagle","correct":false}]',
 'C', 'mcq', 'easy', 4)

ON CONFLICT DO NOTHING;
