drop policy "profiles_own" on "profiles";
create policy "profiles_own" on "profiles" for all using ((id = (select auth.uid()))) with check ((id = (select auth.uid())));
drop policy "tutor_chats_own" on "tutor_chats";
create policy "tutor_chats_own" on "tutor_chats" for all using ((user_id = (select auth.uid()))) with check ((user_id = (select auth.uid())));
drop policy "flashcards_own" on "flashcards";
create policy "flashcards_own" on "flashcards" for all using ((user_id = (select auth.uid()))) with check ((user_id = (select auth.uid())));
drop policy "quiz_own" on "quiz_sessions";
create policy "quiz_own" on "quiz_sessions" for all using ((user_id = (select auth.uid()))) with check ((user_id = (select auth.uid())));
drop policy "exam_own" on "exam_sessions";
create policy "exam_own" on "exam_sessions" for all using ((user_id = (select auth.uid()))) with check ((user_id = (select auth.uid())));
drop policy "sprint_own" on "sprint_sessions";
create policy "sprint_own" on "sprint_sessions" for all using ((user_id = (select auth.uid()))) with check ((user_id = (select auth.uid())));
drop policy "notes_own" on "study_notes";
create policy "notes_own" on "study_notes" for all using ((user_id = (select auth.uid()))) with check ((user_id = (select auth.uid())));
drop policy "mnemonics_own" on "mnemonics";
create policy "mnemonics_own" on "mnemonics" for all using ((user_id = (select auth.uid()))) with check ((user_id = (select auth.uid())));
drop policy "journal_own" on "mistake_journal";
create policy "journal_own" on "mistake_journal" for all using ((user_id = (select auth.uid()))) with check ((user_id = (select auth.uid())));
drop policy "scans_own" on "handwriting_scans";
create policy "scans_own" on "handwriting_scans" for all using ((user_id = (select auth.uid()))) with check ((user_id = (select auth.uid())));
drop policy "user_rewards_own" on "user_rewards";
create policy "user_rewards_own" on "user_rewards" for all using ((user_id = (select auth.uid()))) with check ((user_id = (select auth.uid())));
drop policy "reminders_own" on "study_reminders";
create policy "reminders_own" on "study_reminders" for all using ((user_id = (select auth.uid()))) with check ((user_id = (select auth.uid())));
drop policy "reviews_own" on "app_reviews";
create policy "reviews_own" on "app_reviews" for all using ((user_id = (select auth.uid()))) with check ((user_id = (select auth.uid())));
drop policy "Users manage own roadmaps" on "study_roadmaps";
create policy "Users manage own roadmaps" on "study_roadmaps" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own progress" on "study_roadmap_progress";
create policy "Users manage own progress" on "study_roadmap_progress" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own sessions" on "tutoring_sessions";
create policy "Users manage own sessions" on "tutoring_sessions" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own nodes" on "concept_nodes";
create policy "Users manage own nodes" on "concept_nodes" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own edges" on "concept_edges";
create policy "Users manage own edges" on "concept_edges" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own mastery" on "subtopic_mastery";
create policy "Users manage own mastery" on "subtopic_mastery" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own patterns" on "error_patterns";
create policy "Users manage own patterns" on "error_patterns" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own attempts" on "user_challenge_attempts";
create policy "Users manage own attempts" on "user_challenge_attempts" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own debate sessions" on "debate_sessions";
create policy "Users manage own debate sessions" on "debate_sessions" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own participation" on "tournament_participants";
create policy "Users manage own participation" on "tournament_participants" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own story sessions" on "story_sessions";
create policy "Users manage own story sessions" on "story_sessions" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own streak challenges" on "streak_challenges";
create policy "Users manage own streak challenges" on "streak_challenges" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own streak days" on "streak_challenge_days";
create policy "Users manage own streak days" on "streak_challenge_days" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own attention log" on "topic_attention_log";
create policy "Users manage own attention log" on "topic_attention_log" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own confidence events" on "confidence_events";
create policy "Users manage own confidence events" on "confidence_events" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own predictions" on "exam_predictions";
create policy "Users manage own predictions" on "exam_predictions" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own parent reports" on "parent_reports";
create policy "Users manage own parent reports" on "parent_reports" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "Users manage own teacher exports" on "teacher_exports";
create policy "Users manage own teacher exports" on "teacher_exports" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_memories" on "novo_memories";
create policy "users_own_memories" on "novo_memories" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_lesson_plans" on "lesson_plans";
create policy "users_own_lesson_plans" on "lesson_plans" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_lesson_tasks" on "lesson_plan_tasks";
create policy "users_own_lesson_tasks" on "lesson_plan_tasks" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_certs" on "novo_certifications";
create policy "users_own_certs" on "novo_certifications" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_assessments" on "certification_assessments";
create policy "users_own_assessments" on "certification_assessments" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_proactive" on "novo_proactive_messages";
create policy "users_own_proactive" on "novo_proactive_messages" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "sub_own" on "subscriptions";
create policy "sub_own" on "subscriptions" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "teacher_own" on "teacher_profiles";
create policy "teacher_own" on "teacher_profiles" for all using ((id = (select auth.uid()))) with check ((id = (select auth.uid())));
drop policy "connection_own" on "classroom_connections";
create policy "connection_own" on "classroom_connections" for all using ((teacher_id = (select auth.uid()))) with check ((teacher_id = (select auth.uid())));
drop policy "assignment_teacher_write" on "classroom_assignments";
create policy "assignment_teacher_write" on "classroom_assignments" for all using ((teacher_id = (select auth.uid()))) with check ((teacher_id = (select auth.uid())));
drop policy "calendar_events_own" on "google_calendar_events";
create policy "calendar_events_own" on "google_calendar_events" for all using ((teacher_id = (select auth.uid()))) with check ((teacher_id = (select auth.uid())));
drop policy "gmail_sends_own" on "gmail_sends";
create policy "gmail_sends_own" on "gmail_sends" for all using ((teacher_id = (select auth.uid()))) with check ((teacher_id = (select auth.uid())));
drop policy "drive_files_own" on "google_drive_files";
create policy "drive_files_own" on "google_drive_files" for all using ((teacher_id = (select auth.uid()))) with check ((teacher_id = (select auth.uid())));
drop policy "users_own_topic_performance" on "topic_performance";
create policy "users_own_topic_performance" on "topic_performance" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_snapshots" on "user_snapshots";
create policy "users_own_snapshots" on "user_snapshots" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_confidence" on "quiz_confidence";
create policy "users_own_confidence" on "quiz_confidence" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_session_summaries" on "novo_session_summaries";
create policy "users_own_session_summaries" on "novo_session_summaries" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "classroom_teacher_full" on "classrooms";
create policy "classroom_teacher_full" on "classrooms" for all using (((select auth.uid()) = teacher_id)) with check (((select auth.uid()) = teacher_id));
drop policy "classroom_members_self" on "classroom_members";
create policy "classroom_members_self" on "classroom_members" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "circle_members_self" on "study_circle_members";
create policy "circle_members_self" on "study_circle_members" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "battle_participants" on "battles";
create policy "battle_participants" on "battles" for all using ((((select auth.uid()) = player1_id) OR ((select auth.uid()) = player2_id))) with check ((((select auth.uid()) = player1_id) OR ((select auth.uid()) = player2_id)));
drop policy "xp_snapshots_own" on "xp_snapshots";
create policy "xp_snapshots_own" on "xp_snapshots" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "rivals_own" on "rivals";
create policy "rivals_own" on "rivals" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "bi_participants" on "battle_invites";
create policy "bi_participants" on "battle_invites" for all using ((((select auth.uid()) = challenger_id) OR ((select auth.uid()) = challenged_id))) with check (((select auth.uid()) = challenger_id));
drop policy "bp_own" on "battle_pass";
create policy "bp_own" on "battle_pass" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "fr_own" on "feed_reactions";
create policy "fr_own" on "feed_reactions" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "ta_teacher_manage" on "teacher_assignments";
create policy "ta_teacher_manage" on "teacher_assignments" for all using (((select auth.uid()) = teacher_id)) with check (((select auth.uid()) = teacher_id));
drop policy "ac_student_own" on "assignment_completions";
create policy "ac_student_own" on "assignment_completions" for all using (((select auth.uid()) = student_id)) with check (((select auth.uid()) = student_id));
drop policy "ts_own" on "topic_stats";
create policy "ts_own" on "topic_stats" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "cf_own" on "chat_flashcards";
create policy "cf_own" on "chat_flashcards" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "ce_own" on "concept_explorations";
create policy "ce_own" on "concept_explorations" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "dps_own" on "daily_power_sessions";
create policy "dps_own" on "daily_power_sessions" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "cod_own" on "concept_of_day";
create policy "cod_own" on "concept_of_day" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "mbl_own" on "morning_brief_log";
create policy "mbl_own" on "morning_brief_log" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "sft_own" on "streak_freeze_transactions";
create policy "sft_own" on "streak_freeze_transactions" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "profiles_own_update_secured" on "profiles";
create policy "profiles_own_update_secured" on "profiles" for update using (((select auth.uid()) = id)) with check (((select auth.uid()) = id));
drop policy "friendships_participants" on "friendships";
create policy "friendships_participants" on "friendships" for all using ((((select auth.uid()) = user_id) OR ((select auth.uid()) = friend_id))) with check (((select auth.uid()) = user_id));
drop policy "nudges_participants" on "friend_nudges";
create policy "nudges_participants" on "friend_nudges" for all using ((((select auth.uid()) = from_user) OR ((select auth.uid()) = to_user))) with check (((select auth.uid()) = from_user));
drop policy "checkins_own" on "buddy_checkins";
create policy "checkins_own" on "buddy_checkins" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "circle_messages_members" on "circle_messages";
create policy "circle_messages_members" on "circle_messages" for all using ((EXISTS ( SELECT 1 FROM study_circle_members WHERE ((study_circle_members.circle_id = circle_messages.circle_id) AND (study_circle_members.user_id = (select auth.uid())))))) with check (((select auth.uid()) = user_id));
drop policy "cmr_members" on "circle_message_reactions";
create policy "cmr_members" on "circle_message_reactions" for all using ((EXISTS ( SELECT 1 FROM (circle_messages cm JOIN study_circle_members scm ON ((scm.circle_id = cm.circle_id))) WHERE ((cm.id = circle_message_reactions.message_id) AND (scm.user_id = (select auth.uid())))))) with check (((select auth.uid()) = user_id));
drop policy "lep_own_write" on "live_event_participants";
create policy "lep_own_write" on "live_event_participants" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_mood" on "user_mood_checkins";
create policy "users_own_mood" on "user_mood_checkins" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_boss_fights" on "boss_fight_sessions";
create policy "users_own_boss_fights" on "boss_fight_sessions" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_war_room" on "exam_war_room_sessions";
create policy "users_own_war_room" on "exam_war_room_sessions" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "users_own_dna_reports" on "study_dna_reports";
create policy "users_own_dna_reports" on "study_dna_reports" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "live_rooms_host_write" on "live_study_rooms";
create policy "live_rooms_host_write" on "live_study_rooms" for all using (((select auth.uid()) = host_id)) with check (((select auth.uid()) = host_id));
drop policy "peer_explanations_own" on "peer_explanations";
create policy "peer_explanations_own" on "peer_explanations" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "doubt_votes_own" on "doubt_room_votes";
create policy "doubt_votes_own" on "doubt_room_votes" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "doubt_answers_update_auth" on "doubt_room_answers";
create policy "doubt_answers_update_auth" on "doubt_room_answers" for update using (((select auth.uid()) IS NOT NULL)) with check (((select auth.uid()) IS NOT NULL));
drop policy "doubt_posts_update_views" on "doubt_room_posts";
create policy "doubt_posts_update_views" on "doubt_room_posts" for update using (((select auth.uid()) IS NOT NULL)) with check (((select auth.uid()) IS NOT NULL));
drop policy "moods_own" on "user_moods";
create policy "moods_own" on "user_moods" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "reports_own" on "question_reports";
create policy "reports_own" on "question_reports" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "ab_assign_own" on "ab_assignments";
create policy "ab_assign_own" on "ab_assignments" for all using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
drop policy "inst_admin_all" on "institutions";
create policy "inst_admin_all" on "institutions" for all using (((select auth.uid()) = admin_user_id)) with check (((select auth.uid()) = admin_user_id));
drop policy "inst_mem_admin_write" on "institution_members";
create policy "inst_mem_admin_write" on "institution_members" for all using ((EXISTS ( SELECT 1 FROM institutions i WHERE ((i.id = institution_members.institution_id) AND (i.admin_user_id = (select auth.uid())))))) with check ((EXISTS ( SELECT 1 FROM institutions i WHERE ((i.id = institution_members.institution_id) AND (i.admin_user_id = (select auth.uid()))))));
drop policy "qqf_admin_all" on "question_quality_flags";
create policy "qqf_admin_all" on "question_quality_flags" for all using ((EXISTS ( SELECT 1 FROM user_roles ur WHERE ((ur.user_id = (select auth.uid())) AND (ur.role = ANY (ARRAY['admin'::app_role, 'moderator'::app_role])))))) with check ((EXISTS ( SELECT 1 FROM user_roles ur WHERE ((ur.user_id = (select auth.uid())) AND (ur.role = ANY (ARRAY['admin'::app_role, 'moderator'::app_role]))))));
drop policy "anomaly_admin_all" on "anomaly_flags";
create policy "anomaly_admin_all" on "anomaly_flags" for all using ((EXISTS ( SELECT 1 FROM user_roles ur WHERE ((ur.user_id = (select auth.uid())) AND (ur.role = ANY (ARRAY['admin'::app_role, 'moderator'::app_role])))))) with check ((EXISTS ( SELECT 1 FROM user_roles ur WHERE ((ur.user_id = (select auth.uid())) AND (ur.role = ANY (ARRAY['admin'::app_role, 'moderator'::app_role]))))));
drop policy "vqb_admin_write" on "verified_question_bank";
create policy "vqb_admin_write" on "verified_question_bank" for all using (((EXISTS ( SELECT 1 FROM user_roles ur WHERE ((ur.user_id = (select auth.uid())) AND (ur.role = ANY (ARRAY['admin'::app_role, 'moderator'::app_role]))))) OR (auth.role() = 'service_role'::text))) with check (((EXISTS ( SELECT 1 FROM user_roles ur WHERE ((ur.user_id = (select auth.uid())) AND (ur.role = ANY (ARRAY['admin'::app_role, 'moderator'::app_role]))))) OR (auth.role() = 'service_role'::text)));
