insert into mains_questions (exam, class_level, paper, topic, question_text, word_limit, marks, model_answer, key_points, difficulty) values
('CBSE', '10', 'Science', 'Chemical Reactions', 'Explain why respiration is considered an exothermic reaction. Write balanced equation for aerobic respiration of glucose.', 100, 5,
 'Respiration is exothermic because it releases energy stored in glucose molecules for cellular use, along with heat as a by-product. During aerobic respiration, glucose is broken down completely in presence of oxygen inside mitochondria, releasing a large amount of energy (about 38 ATP molecules) which is far more than what is absorbed to start the reaction. The balanced equation is: C6H12O6 + 6O2 -> 6CO2 + 6H2O + energy. Since energy is given out rather than absorbed, and the products (CO2, H2O) have lower energy than reactants (glucose, O2), the overall process releases net energy, confirming it is exothermic.',
 '["Exothermic means energy is released, not absorbed","Glucose broken down completely in presence of oxygen","Balanced equation C6H12O6 + 6O2 -> 6CO2 + 6H2O + energy","Energy released as ATP and heat","Products have lower energy than reactants"]'::jsonb, 'medium'),

('CBSE', '10', 'Science', 'Life Processes', 'Describe the structure and function of nephron. How does it help in formation of urine?', 120, 5,
 'A nephron is the structural and functional unit of the kidney, consisting of a Bowman capsule surrounding a cluster of capillaries called the glomerulus, and a long renal tubule. Urine formation happens in three steps. First, filtration occurs at the glomerulus where blood pressure forces water, glucose, amino acids, salts and urea from blood into the Bowman capsule, while blood cells and proteins are too large to pass through. Second, selective reabsorption happens along the tubule, where useful substances like glucose, amino acids, and most water are reabsorbed back into blood capillaries surrounding the tubule, while unwanted substances remain. Third, the tubule also secretes additional wastes like H+ and K+ ions directly into the filtrate. The remaining fluid, now concentrated urine containing urea, excess salts and water, passes to the collecting duct and then to the ureter.',
 '["Nephron has Bowman capsule and glomerulus","Filtration removes water, glucose, salts, urea from blood","Blood cells and proteins are not filtered","Selective reabsorption returns useful substances to blood","Tubule secretes additional wastes","Concentrated urine passes to collecting duct"]'::jsonb, 'medium'),

('CBSE', '10', 'Social Science', 'Nationalism in India', 'Explain any three reasons why the Non-Cooperation Movement was withdrawn by Gandhi in February 1922.', 120, 5,
 'Gandhi withdrew the Non-Cooperation Movement mainly due to the Chauri Chaura incident, where on 4 February 1922 a violent mob set fire to a police station killing 22 policemen, in Chauri Chaura, Uttar Pradesh. Gandhi felt that the movement was turning violent, going against the principle of non-violence he insisted the movement should follow, so he called it off to prevent it from spiraling further into violence. Second, he sensed that the movement had reached a stage where without full discipline among participants, it could not be sustained as a peaceful mass struggle, and satyagrahis needed to be properly trained first. Third, Gandhi believed people were not yet ready for mass civil disobedience of the intensity required for the next phase, and that constructive work like promoting khadi, ending untouchability and Hindu-Muslim unity should be prioritised before resuming direct confrontation.',
 '["Chauri Chaura incident 4 February 1922","Police station burned, 22 policemen killed","Gandhi committed to non-violence, called off movement","Movement lacked full satyagrahi discipline","People not yet ready for intense mass civil disobedience","Constructive work prioritised: khadi, anti-untouchability, unity"]'::jsonb, 'medium'),

('CBSE', '10', 'Social Science', 'Resources and Development', 'Discuss any three measures to conserve soil, especially in hilly and arid regions of India.', 100, 5,
 'Soil conservation in hilly regions can be achieved through contour ploughing, where ploughing is done along the contour lines of a slope rather than up and down, which slows down water flow and reduces soil erosion. Terrace farming is another key measure used on steep slopes in hilly areas like the Himalayas and Western Ghats, where the land is cut into a series of flat steps to reduce surface runoff and allow crops to be grown on otherwise unusable steep land. In arid and semi-arid regions, shelter belts are planted, which are rows of trees planted to check wind erosion by stabilising sand dunes and reducing wind speed, commonly seen in western India. Additionally, regulated grazing and controlling overgrazing by cattle helps prevent soil from becoming loose and exposed to erosion in these fragile ecosystems.',
 '["Contour ploughing follows slope contours to slow water flow","Terrace farming used on steep hilly slopes","Shelter belts planted to check wind erosion in arid regions","Regulated grazing prevents overgrazing and soil exposure","Applicable to Himalayan and Western Ghats regions, western arid India"]'::jsonb, 'medium'),

('CBSE', '12', 'Physics', 'Electromagnetic Induction', 'State Faraday laws of electromagnetic induction and use them to explain the working principle of an AC generator.', 120, 5,
 'Faraday first law states that whenever the magnetic flux linked with a circuit changes, an emf is induced in it, lasting only as long as the change continues. Faraday second law states that the magnitude of induced emf is directly proportional to the rate of change of magnetic flux linkage, given by e = -N(dPhi/dt), the negative sign indicating direction is given by Lenz law which opposes the change producing it. An AC generator works on this principle: a rectangular coil is rotated with constant angular velocity inside a uniform magnetic field. As the coil rotates, the angle between the coil plane and the magnetic field continuously changes, so the magnetic flux linked with the coil changes continuously with time. This changing flux induces an alternating emf in the coil as per Faraday laws, which is given by e = e0 sin(omega t), and this alternating emf drives current through an external circuit via slip rings and brushes, producing alternating current.',
 '["Faraday first law: emf induced when flux changes","Faraday second law: e = -N(dPhi/dt)","Negative sign shows Lenz law direction","Coil rotated at constant angular velocity in magnetic field","Continuously changing flux induces alternating emf","e = e0 sin(omega t)","Slip rings and brushes carry current to external circuit"]'::jsonb, 'hard'),

('CBSE', '12', 'Physics', 'Semiconductor Devices', 'With the help of a circuit diagram description, explain the working of a p-n junction diode as a half wave rectifier.', 120, 5,
 'A p-n junction diode conducts current only when forward biased and blocks current when reverse biased, a property used in rectification. In a half wave rectifier circuit, the secondary of a step-down transformer is connected in series with the diode and a load resistance. During the positive half cycle of the AC input, the diode gets forward biased and conducts, so current flows through the load resistance and a voltage appears across it following the shape of the positive half cycle. During the negative half cycle, the diode becomes reverse biased and does not conduct, so no current flows through the load and the output voltage is zero. This means only one half of each input AC cycle appears at the output, converting AC into a pulsating unidirectional output, hence called half wave rectification. The efficiency of a half wave rectifier is low since only half the input waveform is utilised.',
 '["Diode conducts only when forward biased","Positive half cycle: diode forward biased, current flows","Negative half cycle: diode reverse biased, no current","Only one half of input cycle appears at output","Output is pulsating unidirectional (DC-like) not smooth","Half wave rectifier has lower efficiency than full wave"]'::jsonb, 'hard'),

('CBSE', '12', 'Biology', 'Human Reproduction', 'Describe the events of spermatogenesis. Why does meiosis play a crucial role in this process?', 120, 5,
 'Spermatogenesis is the process of formation of spermatozoa from primary germ cells (spermatogonia) inside the seminiferous tubules of the testes. Spermatogonia present on the inner wall of seminiferous tubules multiply by mitosis to increase in number, and some spermatogonia periodically enter meiosis to become primary spermatocytes. Each primary spermatocyte undergoes the first meiotic division (reduction division) to form two equal haploid secondary spermatocytes. The secondary spermatocytes undergo the second meiotic division to produce four equal haploid spermatids. Spermatids are then transformed into spermatozoa through spermiogenesis, and their heads become embedded in Sertoli cells for further maturation, a process called spermiation. Meiosis is crucial because it reduces the chromosome number from diploid to haploid, so that when a haploid sperm fuses with a haploid ovum at fertilisation, the normal diploid chromosome number of the species is restored in the zygote; without meiosis chromosome number would double every generation.',
 '["Spermatogonia multiply by mitosis in seminiferous tubules","Primary spermatocytes formed, undergo first meiotic division","Secondary spermatocytes formed (haploid)","Second meiotic division produces four haploid spermatids","Spermiogenesis transforms spermatids into spermatozoa","Meiosis reduces diploid to haploid number","Restores diploid number at fertilisation, prevents doubling each generation"]'::jsonb, 'hard'),

('CBSE', '12', 'Biology', 'Ecosystem', 'Explain the concept of ecological pyramids. Why is the pyramid of biomass in a marine ecosystem generally inverted?', 100, 5,
 'An ecological pyramid is a graphical representation showing the relationship between different organisms at various trophic levels of an ecosystem in terms of number, biomass, or energy, with producers at the base and successive trophic levels above. The pyramid of biomass in a marine ecosystem is generally inverted because the biomass of producers, mainly phytoplankton, is very small at any given point in time compared to the biomass of consumers like zooplankton and fish above them. This happens because phytoplankton have a very short life span and rapid reproduction rate, so although their standing crop biomass is small at any instant, their productivity over time is high enough to support the larger standing biomass of consumers that live longer and accumulate biomass over a longer period. Therefore, when biomass is measured as a snapshot rather than as production rate over time, the pyramid appears inverted with a small base and wider top.',
 '["Ecological pyramid shows number, biomass, or energy at trophic levels","Producers normally at the base","Marine pyramid of biomass generally inverted","Phytoplankton have small standing biomass despite high productivity","Short life span, rapid reproduction of phytoplankton","Consumers accumulate larger biomass over longer lifespan","Biomass measured as snapshot, not production rate, causes inversion"]'::jsonb, 'hard');
