-- ═══════════════════════════════════════════════════════════════
-- Edora — AI Study Roadmap
-- Personalised week-by-week exam preparation plan.
-- Generated by Gemini, stored as JSONB. Progress tracked per day.
-- Recalibrates when user falls behind.
-- ═══════════════════════════════════════════════════════════════

-- ── 1. study_roadmaps ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.study_roadmaps (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  exam_name             TEXT        NOT NULL,
  exam_date             DATE        NOT NULL,
  plan_summary          TEXT        NOT NULL DEFAULT '',
  subjects              JSONB       NOT NULL DEFAULT '[]',    -- string[]
  weeks                 JSONB       NOT NULL DEFAULT '[]',    -- RoadmapWeek[]
  start_date            DATE        NOT NULL,                 -- day 1 of the plan
  total_days            INTEGER     NOT NULL DEFAULT 0,
  plan_weeks            INTEGER     NOT NULL DEFAULT 0,
  study_days_per_week   INTEGER     NOT NULL DEFAULT 5,
  generated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  recalibrated_at       TIMESTAMPTZ,
  status                TEXT        NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active','archived'))
);

CREATE INDEX IF NOT EXISTS study_roadmaps_user_status_idx
  ON public.study_roadmaps(user_id, status);

-- ── 2. study_roadmap_progress ─────────────────────────────────────────────────
-- One row per study day, updated when user checks off a task.
CREATE TABLE IF NOT EXISTS public.study_roadmap_progress (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  roadmap_id   UUID        NOT NULL REFERENCES public.study_roadmaps(id) ON DELETE CASCADE,
  day_index    INTEGER     NOT NULL,   -- 1-based sequential day number from roadmap
  completed    BOOLEAN     NOT NULL DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  UNIQUE (roadmap_id, day_index)
);

CREATE INDEX IF NOT EXISTS study_roadmap_progress_roadmap_idx
  ON public.study_roadmap_progress(roadmap_id);
CREATE INDEX IF NOT EXISTS study_roadmap_progress_user_idx
  ON public.study_roadmap_progress(user_id);

-- ── 3. RLS — study_roadmaps ───────────────────────────────────────────────────
ALTER TABLE public.study_roadmaps ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public'
      AND tablename='study_roadmaps' AND policyname='Users manage own roadmaps') THEN
    CREATE POLICY "Users manage own roadmaps"
      ON public.study_roadmaps FOR ALL
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ── 4. RLS — study_roadmap_progress ──────────────────────────────────────────
ALTER TABLE public.study_roadmap_progress ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public'
      AND tablename='study_roadmap_progress' AND policyname='Users manage own progress') THEN
    CREATE POLICY "Users manage own progress"
      ON public.study_roadmap_progress FOR ALL
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;
