-- Extended PYQ seed — Part 1: JEE_MAIN (Physics 30, Chemistry 30, Maths 30)

INSERT INTO public.pyq_content
  (exam, year, subject, chapter, question_text, solution_text, options, correct_option, question_type, difficulty, marks)
VALUES

-- ── JEE MAIN · PHYSICS ──────────────────────────────────────────────────────

('JEE_MAIN', 2022, 'Physics', 'Kinematics',
 'A ball is thrown vertically upward with velocity 20 m/s. The maximum height reached is (g = 10 m/s²):',
 'At max height, v = 0. v² = u² − 2gh → 0 = 400 − 20h → h = 20 m.',
 '[{"label":"A","text":"10 m","correct":false},{"label":"B","text":"20 m","correct":true},{"label":"C","text":"40 m","correct":false},{"label":"D","text":"5 m","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Physics', 'Kinematics',
 'A car accelerates uniformly from rest to 20 m/s in 10 s. Distance covered is:',
 's = ut + ½at². u=0, a=2 m/s², t=10. s = 0 + ½×2×100 = 100 m.',
 '[{"label":"A","text":"200 m","correct":false},{"label":"B","text":"50 m","correct":false},{"label":"C","text":"100 m","correct":true},{"label":"D","text":"40 m","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Physics', 'Work Energy Theorem',
 'A 2 kg block slides down a frictionless incline of height 5 m. Its speed at the bottom is (g = 10 m/s²):',
 'Energy conservation: mgh = ½mv². v = √(2gh) = √(100) = 10 m/s.',
 '[{"label":"A","text":"5 m/s","correct":false},{"label":"B","text":"10 m/s","correct":true},{"label":"C","text":"√50 m/s","correct":false},{"label":"D","text":"20 m/s","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Physics', 'Rotational Motion',
 'A disc of mass M and radius R has moment of inertia about its centre:',
 'Standard result for a solid disc: I = MR²/2.',
 '[{"label":"A","text":"MR²","correct":false},{"label":"B","text":"MR²/4","correct":false},{"label":"C","text":"MR²/2","correct":true},{"label":"D","text":"2MR²/3","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Physics', 'Fluid Mechanics',
 'According to Bernoulli''s theorem, for a streamlined fluid flow, which quantity remains constant?',
 'Bernoulli''s theorem: P + ½ρv² + ρgh = constant along a streamline. Total mechanical energy per unit volume is conserved.',
 '[{"label":"A","text":"Pressure only","correct":false},{"label":"B","text":"Velocity only","correct":false},{"label":"C","text":"P + ½ρv² + ρgh","correct":true},{"label":"D","text":"ρgh only","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_MAIN', 2021, 'Physics', 'Thermal Physics',
 'The root mean square speed of gas molecules is proportional to:',
 'v_rms = √(3RT/M). So v_rms ∝ √T where T is absolute temperature.',
 '[{"label":"A","text":"T","correct":false},{"label":"B","text":"√T","correct":true},{"label":"C","text":"T²","correct":false},{"label":"D","text":"1/T","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Physics', 'Kinetic Theory',
 'The average kinetic energy of a monatomic ideal gas molecule at temperature T is:',
 'For a monatomic gas, degrees of freedom = 3. KE = (3/2)k_BT per molecule.',
 '[{"label":"A","text":"½k_BT","correct":false},{"label":"B","text":"k_BT","correct":false},{"label":"C","text":"(3/2)k_BT","correct":true},{"label":"D","text":"3k_BT","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Physics', 'Alternating Current',
 'In a purely resistive AC circuit, the phase difference between current and voltage is:',
 'In a pure resistor, voltage and current are in phase. Phase difference = 0.',
 '[{"label":"A","text":"π/2","correct":false},{"label":"B","text":"π","correct":false},{"label":"C","text":"π/4","correct":false},{"label":"D","text":"0","correct":true}]',
 'D', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Physics', 'Alternating Current',
 'The resonant frequency of an LC circuit with L = 1 mH and C = 1 μF is:',
 'f = 1/(2π√LC) = 1/(2π√(10⁻³ × 10⁻⁶)) = 1/(2π × 10⁻⁴·⁵) ≈ 1/(2π × 31.6 × 10⁻⁶) ≈ 5033 Hz ≈ 5 kHz.',
 '[{"label":"A","text":"≈ 5 kHz","correct":true},{"label":"B","text":"≈ 50 Hz","correct":false},{"label":"C","text":"≈ 500 Hz","correct":false},{"label":"D","text":"≈ 50 kHz","correct":false}]',
 'A', 'mcq', 'hard', 4),

('JEE_MAIN', 2021, 'Physics', 'Wave Optics',
 'In Young''s double slit experiment, fringe width β is given by (D = screen distance, d = slit separation, λ = wavelength):',
 'Fringe width β = λD/d. This is the standard derivation from path difference analysis.',
 '[{"label":"A","text":"β = λd/D","correct":false},{"label":"B","text":"β = λD/d","correct":true},{"label":"C","text":"β = dD/λ","correct":false},{"label":"D","text":"β = d/(λD)","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Physics', 'Wave Optics',
 'The condition for destructive interference is that the path difference equals:',
 'Destructive interference: path difference = (2n+1)λ/2 = (n+½)λ where n = 0,1,2,...',
 '[{"label":"A","text":"nλ","correct":false},{"label":"B","text":"(2n+1)λ/2","correct":true},{"label":"C","text":"2nλ","correct":false},{"label":"D","text":"nλ/2","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Physics', 'Dual Nature of Matter',
 'The photoelectric effect demonstrates the:',
 'Photoelectric effect: electrons emitted when light hits metal surface. This proves light has particle (photon) nature. Einstein explained it as E = hν.',
 '[{"label":"A","text":"Wave nature of light","correct":false},{"label":"B","text":"Particle nature of light","correct":true},{"label":"C","text":"Polarisation of light","correct":false},{"label":"D","text":"Diffraction of light","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Physics', 'Atoms',
 'According to Bohr''s model, the radius of the nth orbit of hydrogen atom is proportional to:',
 'r_n = n²a₀ where a₀ = 0.529 Å. So r_n ∝ n².',
 '[{"label":"A","text":"n","correct":false},{"label":"B","text":"n²","correct":true},{"label":"C","text":"n³","correct":false},{"label":"D","text":"1/n","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Physics', 'Nuclei',
 'The half-life of a radioactive substance is 20 min. After 1 hour, the fraction remaining is:',
 '1 hour = 60 min = 3 half-lives. Fraction = (1/2)³ = 1/8.',
 '[{"label":"A","text":"1/4","correct":false},{"label":"B","text":"1/6","correct":false},{"label":"C","text":"1/8","correct":true},{"label":"D","text":"1/16","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_MAIN', 2023, 'Physics', 'Semiconductors',
 'In a p-n junction diode, the depletion layer is formed due to:',
 'Depletion layer forms when electrons from n-side diffuse to p-side and holes from p-side diffuse to n-side, creating a region depleted of mobile charge carriers.',
 '[{"label":"A","text":"Drift of majority carriers","correct":false},{"label":"B","text":"Diffusion of majority carriers","correct":true},{"label":"C","text":"Drift of minority carriers","correct":false},{"label":"D","text":"External electric field","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_MAIN', 2021, 'Physics', 'Electromagnetic Induction',
 'A coil of 100 turns has flux change of 0.02 Wb in 0.1 s. The induced EMF is:',
 'EMF = −N × dΦ/dt = 100 × 0.02/0.1 = 100 × 0.2 = 20 V.',
 '[{"label":"A","text":"2 V","correct":false},{"label":"B","text":"0.2 V","correct":false},{"label":"C","text":"20 V","correct":true},{"label":"D","text":"200 V","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Physics', 'Electromagnetic Waves',
 'Which electromagnetic wave has the highest frequency?',
 'Frequency order (low to high): Radio < Microwave < IR < Visible < UV < X-ray < Gamma rays.',
 '[{"label":"A","text":"X-rays","correct":false},{"label":"B","text":"Microwaves","correct":false},{"label":"C","text":"Gamma rays","correct":true},{"label":"D","text":"UV rays","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Physics', 'Ray Optics',
 'Total internal reflection occurs when light travels from:',
 'TIR occurs when light goes from denser to rarer medium at angle ≥ critical angle.',
 '[{"label":"A","text":"Rarer to denser medium","correct":false},{"label":"B","text":"Denser to rarer medium at angle ≥ critical angle","correct":true},{"label":"C","text":"Any medium to vacuum","correct":false},{"label":"D","text":"Vacuum to any medium","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Physics', 'Properties of Solids',
 'Young''s modulus is defined as the ratio of:',
 'Young''s modulus Y = Longitudinal stress / Longitudinal strain = (F/A) / (ΔL/L).',
 '[{"label":"A","text":"Shear stress to shear strain","correct":false},{"label":"B","text":"Bulk stress to volumetric strain","correct":false},{"label":"C","text":"Longitudinal stress to longitudinal strain","correct":true},{"label":"D","text":"Lateral strain to longitudinal strain","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Physics', 'Gravitation',
 'The gravitational potential energy between two masses M and m separated by distance r is:',
 'U = −GMm/r. Negative sign indicates bound system (attractive force).',
 '[{"label":"A","text":"GMm/r","correct":false},{"label":"B","text":"−GMm/r²","correct":false},{"label":"C","text":"−GMm/r","correct":true},{"label":"D","text":"GMm/r²","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Physics', 'Laws of Motion',
 'A body is in equilibrium. Which of the following is necessarily true?',
 'Equilibrium: ΣF = 0 (net force = 0) AND Στ = 0 (net torque = 0). Both conditions needed.',
 '[{"label":"A","text":"Body is at rest","correct":false},{"label":"B","text":"Net force and net torque are both zero","correct":true},{"label":"C","text":"Body moves with constant acceleration","correct":false},{"label":"D","text":"All forces are equal","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_MAIN', 2023, 'Physics', 'Projectile Motion',
 'A projectile is launched at 45° to horizontal with speed u. The range is:',
 'R = u²sin(2θ)/g. At θ = 45°: sin(90°) = 1. R = u²/g.',
 '[{"label":"A","text":"u²/2g","correct":false},{"label":"B","text":"u²/g","correct":true},{"label":"C","text":"2u²/g","correct":false},{"label":"D","text":"u²sin45°/g","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Physics', 'Surface Tension',
 'The excess pressure inside a soap bubble of radius R with surface tension T is:',
 'Soap bubble has two surfaces. Excess pressure = 4T/R (factor of 2 for each surface, so 2 × 2T/R = 4T/R).',
 '[{"label":"A","text":"T/R","correct":false},{"label":"B","text":"2T/R","correct":false},{"label":"C","text":"4T/R","correct":true},{"label":"D","text":"6T/R","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_MAIN', 2021, 'Physics', 'Calorimetry',
 'Specific heat of water is 4200 J/kg·K. Heat needed to raise 2 kg of water by 10°C is:',
 'Q = mcΔT = 2 × 4200 × 10 = 84000 J = 84 kJ.',
 '[{"label":"A","text":"840 J","correct":false},{"label":"B","text":"8400 J","correct":false},{"label":"C","text":"84000 J","correct":true},{"label":"D","text":"420 J","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Physics', 'Current Electricity',
 'A battery of EMF 12 V has internal resistance 1 Ω. When connected to external 5 Ω, the terminal voltage is:',
 'I = E/(R+r) = 12/6 = 2 A. Terminal voltage = E − Ir = 12 − 2×1 = 10 V.',
 '[{"label":"A","text":"12 V","correct":false},{"label":"B","text":"10 V","correct":true},{"label":"C","text":"2 V","correct":false},{"label":"D","text":"6 V","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_MAIN', 2022, 'Physics', 'Electrostatics',
 'The work done in moving a charge of 3 C through a potential difference of 4 V is:',
 'W = qV = 3 × 4 = 12 J.',
 '[{"label":"A","text":"4 J","correct":false},{"label":"B","text":"3 J","correct":false},{"label":"C","text":"12 J","correct":true},{"label":"D","text":"7 J","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Physics', 'Magnetism',
 'A current-carrying solenoid behaves like a:',
 'A solenoid with current flowing has two poles (N and S) at its ends, just like a bar magnet.',
 '[{"label":"A","text":"Electric dipole","correct":false},{"label":"B","text":"Bar magnet","correct":true},{"label":"C","text":"Capacitor","correct":false},{"label":"D","text":"Toroid","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Physics', 'Oscillations',
 'The time period of a simple pendulum of length L is (g = acceleration due to gravity):',
 'T = 2π√(L/g). This is derived from restoring force = mg sinθ ≈ mgθ for small angles.',
 '[{"label":"A","text":"2π√(g/L)","correct":false},{"label":"B","text":"π√(L/g)","correct":false},{"label":"C","text":"2π√(L/g)","correct":true},{"label":"D","text":"2π√(L/2g)","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Physics', 'Waves',
 'The speed of sound in air at 0°C is 332 m/s. At 100°C it will be approximately:',
 'v ∝ √T. v₂/v₁ = √(373/273). v₂ = 332 × √(1.366) ≈ 332 × 1.169 ≈ 388 m/s.',
 '[{"label":"A","text":"332 m/s","correct":false},{"label":"B","text":"365 m/s","correct":false},{"label":"C","text":"388 m/s","correct":true},{"label":"D","text":"410 m/s","correct":false}]',
 'C', 'mcq', 'hard', 4),

('JEE_MAIN', 2021, 'Physics', 'Nuclear Physics',
 'In beta-minus decay, an atom emits:',
 'β⁻ decay: n → p + e⁻ + antineutrino. The nucleus emits an electron (beta particle) and an antineutrino.',
 '[{"label":"A","text":"A proton","correct":false},{"label":"B","text":"An alpha particle","correct":false},{"label":"C","text":"An electron and antineutrino","correct":true},{"label":"D","text":"A positron and neutrino","correct":false}]',
 'C', 'mcq', 'medium', 4),

-- ── JEE MAIN · CHEMISTRY ────────────────────────────────────────────────────

('JEE_MAIN', 2021, 'Chemistry', 'Redox Reactions',
 'In the reaction MnO₄⁻ + Fe²⁺ → Mn²⁺ + Fe³⁺ (acidic medium), the oxidation state of Mn changes from:',
 'In KMnO₄, Mn is +7. In Mn²⁺, it is +2. Change = +7 to +2 (reduction). Fe²⁺ → Fe³⁺ (oxidation).',
 '[{"label":"A","text":"+7 to +4","correct":false},{"label":"B","text":"+7 to +2","correct":true},{"label":"C","text":"+4 to +2","correct":false},{"label":"D","text":"+6 to +2","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_MAIN', 2022, 'Chemistry', 'p-Block Elements',
 'Which of the following is the strongest acid among the halogen acids?',
 'Acid strength of HF < HCl < HBr < HI. HI is strongest because H−I bond is weakest (longest, easiest to break).',
 '[{"label":"A","text":"HF","correct":false},{"label":"B","text":"HCl","correct":false},{"label":"C","text":"HBr","correct":false},{"label":"D","text":"HI","correct":true}]',
 'D', 'mcq', 'medium', 4),

('JEE_MAIN', 2023, 'Chemistry', 's-Block Elements',
 'Which alkali metal reacts most vigorously with water?',
 'Reactivity of alkali metals increases down the group: Li < Na < K < Rb < Cs. Caesium reacts most vigorously.',
 '[{"label":"A","text":"Lithium","correct":false},{"label":"B","text":"Sodium","correct":false},{"label":"C","text":"Potassium","correct":false},{"label":"D","text":"Caesium","correct":true}]',
 'D', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Chemistry', 'Surface Chemistry',
 'Which of the following is an example of an emulsion?',
 'Emulsion = liquid dispersed in liquid. Milk is oil-in-water emulsion. Smoke = solid in gas, fog = liquid in gas, pumice = gas in solid.',
 '[{"label":"A","text":"Smoke","correct":false},{"label":"B","text":"Fog","correct":false},{"label":"C","text":"Milk","correct":true},{"label":"D","text":"Pumice stone","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Chemistry', 'Polymers',
 'Nylon-6,6 is formed by condensation of:',
 'Nylon-6,6 = condensation polymer of hexamethylene diamine (6 C) + adipic acid (6 C). Amide bonds form with loss of water.',
 '[{"label":"A","text":"Caprolactam","correct":false},{"label":"B","text":"Hexamethylene diamine and adipic acid","correct":true},{"label":"C","text":"Ethylene glycol and terephthalic acid","correct":false},{"label":"D","text":"Styrene and butadiene","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_MAIN', 2023, 'Chemistry', 'Biomolecules',
 'The secondary structure of proteins refers to:',
 'Secondary structure = local folding into α-helix or β-pleated sheet, stabilised by hydrogen bonds between NH and C=O groups.',
 '[{"label":"A","text":"Sequence of amino acids","correct":false},{"label":"B","text":"α-helix and β-sheet structures","correct":true},{"label":"C","text":"3D folding of entire chain","correct":false},{"label":"D","text":"Quaternary arrangement of subunits","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_MAIN', 2021, 'Chemistry', 'Alcohols and Ethers',
 'The reaction of ethanol with conc. H₂SO₄ at 170°C gives:',
 'At 170°C (higher temperature), intermolecular dehydration does not occur; instead intramolecular dehydration gives ethylene (CH₂=CH₂). At 140°C, ether forms.',
 '[{"label":"A","text":"Diethyl ether","correct":false},{"label":"B","text":"Ethylene","correct":true},{"label":"C","text":"Acetaldehyde","correct":false},{"label":"D","text":"Acetic acid","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_MAIN', 2022, 'Chemistry', 'Aldehydes and Ketones',
 'Which test distinguishes an aldehyde from a ketone?',
 'Tollens'' test (silver mirror test): aldehydes reduce [Ag(NH₃)₂]⁺ to Ag metal. Ketones do not react.',
 '[{"label":"A","text":"2,4-DNP test","correct":false},{"label":"B","text":"Tollens'' test","correct":true},{"label":"C","text":"Lucas test","correct":false},{"label":"D","text":"Victor Meyer test","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Chemistry', 'Amines',
 'The basicity order among aliphatic amines in aqueous solution is:',
 'In aqueous solution, basicity: secondary amine > primary amine > tertiary amine > NH₃ (due to steric and solvation effects). So (CH₃)₂NH > CH₃NH₂ > (CH₃)₃N > NH₃.',
 '[{"label":"A","text":"3° > 2° > 1° > NH₃","correct":false},{"label":"B","text":"1° > 2° > 3° > NH₃","correct":false},{"label":"C","text":"2° > 1° > 3° > NH₃","correct":true},{"label":"D","text":"NH₃ > 1° > 2° > 3°","correct":false}]',
 'C', 'mcq', 'hard', 4),

('JEE_MAIN', 2021, 'Chemistry', 'Carboxylic Acids',
 'Formic acid (HCOOH) is stronger than acetic acid (CH₃COOH) because:',
 'CH₃ group is electron-donating (inductive effect), which destabilises the carboxylate anion and decreases acid strength. Formic acid lacks this group, so it is stronger (pKa HCOOH = 3.74, CH₃COOH = 4.74).',
 '[{"label":"A","text":"Formic acid has higher molecular mass","correct":false},{"label":"B","text":"Methyl group donates electrons, reducing acid strength of acetic acid","correct":true},{"label":"C","text":"Formic acid has two oxygen atoms","correct":false},{"label":"D","text":"Acetic acid undergoes esterification","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_MAIN', 2022, 'Chemistry', 'Organic Chemistry - Halides',
 'SN2 reaction is favoured by:',
 'SN2: bimolecular nucleophilic substitution. Favoured by primary alkyl halides (less steric hindrance), strong nucleophiles, and polar aprotic solvents.',
 '[{"label":"A","text":"Tertiary alkyl halides","correct":false},{"label":"B","text":"Primary alkyl halides with strong nucleophile","correct":true},{"label":"C","text":"Weak nucleophiles in polar protic solvents","correct":false},{"label":"D","text":"Carbocation intermediate","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_MAIN', 2023, 'Chemistry', 'Aromatic Compounds',
 'Benzene undergoes electrophilic aromatic substitution because:',
 'Benzene''s π-electron cloud makes it electron-rich, readily attacked by electrophiles. It prefers substitution (not addition) to preserve aromaticity.',
 '[{"label":"A","text":"It has sp³ hybridised carbons","correct":false},{"label":"B","text":"Its π-electron cloud is electron-rich and prefers substitution to retain aromaticity","correct":true},{"label":"C","text":"It is aliphatic in nature","correct":false},{"label":"D","text":"It undergoes nucleophilic addition","correct":false}]',
 'B', 'mcq', 'medium', 4),

('JEE_MAIN', 2021, 'Chemistry', 'Electrochemistry',
 'The amount of substance deposited at an electrode during electrolysis is given by:',
 'Faraday''s first law: m = ZIt = (M/nF)It. Mass is proportional to charge passed (I×t).',
 '[{"label":"A","text":"Faraday''s first law: m ∝ charge passed","correct":true},{"label":"B","text":"Ohm''s law","correct":false},{"label":"C","text":"Nernst equation","correct":false},{"label":"D","text":"Henderson equation","correct":false}]',
 'A', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Chemistry', 'Chemical Kinetics',
 'For a first-order reaction, the half-life is:',
 't₁/₂ = 0.693/k for first-order reaction. It is independent of initial concentration.',
 '[{"label":"A","text":"t₁/₂ = 1/(k[A]₀)","correct":false},{"label":"B","text":"t₁/₂ = 0.693/k","correct":true},{"label":"C","text":"t₁/₂ = [A]₀/(2k)","correct":false},{"label":"D","text":"t₁/₂ = 2/(k[A]₀)","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Chemistry', 'Solid State',
 'A body-centred cubic (BCC) unit cell contains how many atoms?',
 'BCC: 8 corner atoms × 1/8 + 1 body-centre atom × 1 = 1 + 1 = 2 atoms per unit cell.',
 '[{"label":"A","text":"1","correct":false},{"label":"B","text":"2","correct":true},{"label":"C","text":"4","correct":false},{"label":"D","text":"3","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Chemistry', 'd-Block Elements',
 'Which of the following transition metals has the highest melting point?',
 'Tungsten (W) has the highest melting point of all metals at 3422°C, due to very strong metallic bonds from d-orbital overlap.',
 '[{"label":"A","text":"Iron","correct":false},{"label":"B","text":"Chromium","correct":false},{"label":"C","text":"Tungsten","correct":true},{"label":"D","text":"Copper","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_MAIN', 2022, 'Chemistry', 'p-Block Elements',
 'Which allotrope of carbon is the hardest substance?',
 'Diamond is the hardest natural substance. Each carbon is sp³ hybridised, forming a tetrahedral covalent network solid extending in 3D.',
 '[{"label":"A","text":"Graphite","correct":false},{"label":"B","text":"Fullerene","correct":false},{"label":"C","text":"Coal","correct":false},{"label":"D","text":"Diamond","correct":true}]',
 'D', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Chemistry', 'Acids and Bases',
 'The pH of a 0.01 M HCl solution is:',
 'HCl is a strong acid, fully dissociated. [H⁺] = 0.01 = 10⁻² M. pH = −log[H⁺] = 2.',
 '[{"label":"A","text":"1","correct":false},{"label":"B","text":"2","correct":true},{"label":"C","text":"12","correct":false},{"label":"D","text":"7","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Chemistry', 'Hydrogen',
 'Heavy water (D₂O) differs from ordinary water (H₂O) in that:',
 'D₂O contains deuterium (²H) instead of protium (¹H). It has higher density, boiling point, and melting point. D₂O is used as moderator in nuclear reactors.',
 '[{"label":"A","text":"It is radioactive","correct":false},{"label":"B","text":"It contains deuterium instead of protium","correct":true},{"label":"C","text":"It has lower density than H₂O","correct":false},{"label":"D","text":"It cannot form hydrogen bonds","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Chemistry', 'Environmental Chemistry',
 'The major cause of photochemical smog is:',
 'Photochemical smog forms from NOₓ and hydrocarbons in sunlight, producing ozone, PAN (peroxyacetyl nitrate), and other oxidants.',
 '[{"label":"A","text":"SO₂ and water vapour","correct":false},{"label":"B","text":"CO₂ and methane","correct":false},{"label":"C","text":"NOₓ and hydrocarbons reacting in sunlight","correct":true},{"label":"D","text":"CFC compounds","correct":false}]',
 'C', 'mcq', 'easy', 4),

-- ── JEE MAIN · MATHEMATICS ──────────────────────────────────────────────────

('JEE_MAIN', 2022, 'Maths', 'Quadratic Equations',
 'The roots of x² − 5x + 6 = 0 are:',
 'x² − 5x + 6 = (x−2)(x−3) = 0. Roots: x = 2, x = 3.',
 '[{"label":"A","text":"2 and 3","correct":true},{"label":"B","text":"−2 and −3","correct":false},{"label":"C","text":"1 and 6","correct":false},{"label":"D","text":"2 and −3","correct":false}]',
 'A', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Maths', 'Sets and Relations',
 'If A = {1,2,3} and B = {2,3,4}, then A ∩ B is:',
 'A ∩ B = elements common to both sets = {2, 3}.',
 '[{"label":"A","text":"{1,2,3,4}","correct":false},{"label":"B","text":"{2,3}","correct":true},{"label":"C","text":"{1,4}","correct":false},{"label":"D","text":"{}","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Maths', 'Functions',
 'If f(x) = 2x + 3, then f⁻¹(x) is:',
 'Let y = 2x+3. Then x = (y−3)/2. So f⁻¹(x) = (x−3)/2.',
 '[{"label":"A","text":"(x+3)/2","correct":false},{"label":"B","text":"(x−3)/2","correct":true},{"label":"C","text":"2x−3","correct":false},{"label":"D","text":"1/(2x+3)","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Maths', 'Logarithms',
 'log₁₀(1000) equals:',
 'log₁₀(1000) = log₁₀(10³) = 3.',
 '[{"label":"A","text":"2","correct":false},{"label":"B","text":"4","correct":false},{"label":"C","text":"3","correct":true},{"label":"D","text":"100","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Maths', 'Circles',
 'The equation x² + y² = 25 represents a circle with radius:',
 'x² + y² = r². Comparing: r² = 25, r = 5.',
 '[{"label":"A","text":"25","correct":false},{"label":"B","text":"5","correct":true},{"label":"C","text":"√5","correct":false},{"label":"D","text":"10","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Maths', 'Conic Sections',
 'The eccentricity of a circle is:',
 'For a circle, e = 0. Ellipse: 0 < e < 1. Parabola: e = 1. Hyperbola: e > 1.',
 '[{"label":"A","text":"1","correct":false},{"label":"B","text":"0","correct":true},{"label":"C","text":"Greater than 1","correct":false},{"label":"D","text":"Less than 1 but not 0","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Maths', '3D Geometry',
 'The distance between points (1,2,3) and (4,6,3) is:',
 'd = √((4−1)² + (6−2)² + (3−3)²) = √(9+16+0) = √25 = 5.',
 '[{"label":"A","text":"7","correct":false},{"label":"B","text":"5","correct":true},{"label":"C","text":"√7","correct":false},{"label":"D","text":"25","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Maths', 'Vectors',
 'The magnitude of vector 3i + 4j is:',
 '|v| = √(3² + 4²) = √(9+16) = √25 = 5.',
 '[{"label":"A","text":"7","correct":false},{"label":"B","text":"5","correct":true},{"label":"C","text":"12","correct":false},{"label":"D","text":"√7","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Maths', 'Statistics',
 'The median of the data set {3, 1, 4, 1, 5, 9, 2, 6} is:',
 'Sorted: {1,1,2,3,4,5,6,9}. n=8. Median = average of 4th and 5th = (3+4)/2 = 3.5.',
 '[{"label":"A","text":"3","correct":false},{"label":"B","text":"4","correct":false},{"label":"C","text":"3.5","correct":true},{"label":"D","text":"5","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_MAIN', 2022, 'Maths', 'Mathematical Reasoning',
 'The contrapositive of "If p then q" is:',
 'Contrapositive of p→q is ¬q→¬p (if not q, then not p). It is logically equivalent to the original.',
 '[{"label":"A","text":"If q then p","correct":false},{"label":"B","text":"If not p then not q","correct":false},{"label":"C","text":"If not q then not p","correct":true},{"label":"D","text":"Not p and not q","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_MAIN', 2021, 'Maths', 'Calculus - Derivatives',
 'd/dx(eˣ) equals:',
 'The derivative of eˣ is eˣ itself. This is unique property of the exponential function.',
 '[{"label":"A","text":"xeˣ","correct":false},{"label":"B","text":"eˣ⁻¹","correct":false},{"label":"C","text":"eˣ","correct":true},{"label":"D","text":"e","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Maths', 'Calculus - Derivatives',
 'If y = sin x, then dy/dx is:',
 'd/dx(sin x) = cos x.',
 '[{"label":"A","text":"−sin x","correct":false},{"label":"B","text":"cos x","correct":true},{"label":"C","text":"−cos x","correct":false},{"label":"D","text":"tan x","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Maths', 'Calculus - Integration',
 '∫eˣ dx equals:',
 '∫eˣ dx = eˣ + C.',
 '[{"label":"A","text":"eˣ/x + C","correct":false},{"label":"B","text":"xeˣ + C","correct":false},{"label":"C","text":"eˣ + C","correct":true},{"label":"D","text":"eˣ⁺¹ + C","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Maths', 'Differential Equations',
 'The degree of the differential equation (d²y/dx²)³ + (dy/dx)² = 0 is:',
 'Degree = power of the highest order derivative after making it free from radicals. Highest derivative = d²y/dx², its power = 3. Degree = 3.',
 '[{"label":"A","text":"1","correct":false},{"label":"B","text":"2","correct":false},{"label":"C","text":"3","correct":true},{"label":"D","text":"6","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_MAIN', 2022, 'Maths', 'Matrices and Determinants',
 'If matrix A is of order 2×3 and B is 3×4, then AB has order:',
 'Product AB is defined when columns of A = rows of B. Here 3=3. Order of AB = rows of A × cols of B = 2×4.',
 '[{"label":"A","text":"2×4","correct":true},{"label":"B","text":"3×4","correct":false},{"label":"C","text":"2×3","correct":false},{"label":"D","text":"3×3","correct":false}]',
 'A', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Maths', 'Probability',
 'Two cards are drawn from a pack of 52 without replacement. Probability both are kings is:',
 'P = (4/52) × (3/51) = 12/2652 = 1/221.',
 '[{"label":"A","text":"1/169","correct":false},{"label":"B","text":"1/221","correct":true},{"label":"C","text":"1/52","correct":false},{"label":"D","text":"4/52","correct":false}]',
 'B', 'mcq', 'hard', 4),

('JEE_MAIN', 2021, 'Maths', 'Trigonometry',
 'The value of sin 30° × cos 60° is:',
 'sin 30° = 1/2, cos 60° = 1/2. Product = 1/4.',
 '[{"label":"A","text":"1/2","correct":false},{"label":"B","text":"1/4","correct":true},{"label":"C","text":"√3/4","correct":false},{"label":"D","text":"1","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2022, 'Maths', 'Straight Lines',
 'The equation of line passing through origin with slope 3 is:',
 'y = mx. With m=3: y = 3x.',
 '[{"label":"A","text":"y = 3x + 1","correct":false},{"label":"B","text":"y = x/3","correct":false},{"label":"C","text":"y = 3x","correct":true},{"label":"D","text":"x = 3y","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Maths', 'Sequences and Series',
 'The sum of infinite geometric series with first term a = 1 and common ratio r = 1/2 is:',
 'S∞ = a/(1−r) = 1/(1−1/2) = 1/(1/2) = 2.',
 '[{"label":"A","text":"1","correct":false},{"label":"B","text":"3","correct":false},{"label":"C","text":"2","correct":true},{"label":"D","text":"∞","correct":false}]',
 'C', 'mcq', 'easy', 4),

('JEE_MAIN', 2021, 'Maths', 'Calculus - Limits',
 'lim(x→0) (1 − cos x)/x² equals:',
 'Using L''Hopital or expansion: 1 − cos x ≈ x²/2 for small x. So limit = (x²/2)/x² = 1/2.',
 '[{"label":"A","text":"0","correct":false},{"label":"B","text":"1","correct":false},{"label":"C","text":"1/2","correct":true},{"label":"D","text":"2","correct":false}]',
 'C', 'mcq', 'medium', 4),

('JEE_MAIN', 2022, 'Maths', 'Binomial Theorem',
 'The number of terms in the expansion of (a + b)¹⁰ is:',
 'Number of terms in (a+b)ⁿ = n+1 = 10+1 = 11.',
 '[{"label":"A","text":"10","correct":false},{"label":"B","text":"11","correct":true},{"label":"C","text":"20","correct":false},{"label":"D","text":"9","correct":false}]',
 'B', 'mcq', 'easy', 4),

('JEE_MAIN', 2023, 'Maths', 'Complex Numbers',
 'The modulus of the complex number 3 + 4i is:',
 '|z| = √(3² + 4²) = √(9+16) = √25 = 5.',
 '[{"label":"A","text":"7","correct":false},{"label":"B","text":"3","correct":false},{"label":"C","text":"5","correct":true},{"label":"D","text":"4","correct":false}]',
 'C', 'mcq', 'easy', 4)

ON CONFLICT DO NOTHING;
